### PR TITLE
Article - NodeJS Environment Variables

### PR DESCRIPTION
**Pull request by cyberShaw**
Add an article about environment variables in Node and how to use them in a deployed application.
Please review and merge 😄

### CODE REVIEW

**Comment by ninjaginja** [comment]
@auxesis Are we able to supply any Section screenshots to replace the Netlify images in this article?

**Comment by auxesis** [comment]
@ninjaginja we don't have anything available just yet. 

I'd be happy to ship the article now with Netlify references, and swap it out later on once we have those screens built.

**Comment by auxesis** [comment]
@cyberShaw thank you for submitting this article! 🎉 

If you have time, I would love to see two follow up articles: 

- A tutorial on using [ejson](https://github.com/Shopify/ejson) to manage secrets developers often put in environment variables
- A compare/contrast of ejson vs environment variables, for managing configuration and secrets.

**Comment by cyberShaw** [comment]
> @cyberShaw thank you for submitting this article! 🎉 
> 
> If you have time, I would love to see two follow up articles: 
> 
> - A tutorial on using [ejson](https://github.com/Shopify/ejson) to manage secrets developers often put in environment variables
> - A compare/contrast of ejson vs environment variables, for managing configuration and secrets.  

Sounds awesome. I'll start looking into ejson and doing some reading. We'll make it a series. ✨

**Pull request merged**
