### PR TITLE
Graph Implementation and Traversal Algorithms (Java)

### PR DESCRIPTION
**Pull request by tensoncai**
#### Preliminary Checks - Formatting and Structure 
- [x] Does your article follow any of the suggested structure formats? - **see [example formats](https://github.com/section-io/engineering-education/blob/master/CONTRIBUTING.md#example-format-structure)**
- [x] Is your article properly formatted in Markdown? - **see [Github Markdown guide](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet)**
- [x] Have you used the correct folder and file structure? - **see [Contribution Guidelines](https://github.com/section-io/engineering-education/blob/master/CONTRIBUTING.md)**
- [x] Is your article over 750 words? - **Tool**: [Wordcounter.net](https://wordcounter.net)
- [x] Have you used our preferred heading structure? - **[H3 (###) and up](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet#headers)**
- [x] Does your article provide enough value and detail about your topic? - **Articles should be clear, accurate, and fully explained.**
- [x] Can your article be understood by beginners? - **Assume the audience is smart but has no prior exposure to the common terminology in your article.**
- [x] Have you included a hero image that is 600x400 pixels and have the copyright to use it? - **Tools:** [Pixlr Image Editor](https://pixlr.com/e) for resizing and [Unsplash](https://unsplash.com) for Creative Commons images
- [x] In your PR - add a comment that states **["This fixes #(enter your Idea Content Form #)"](https://youtu.be/TKJ4RdhyB5Y?t=278)** to link and close your Idea Content (issue) when the PR is merged.

**NOTE: (1st time contributors - submit ONLY one article to get familiar with the process and style-once published, you can then submit any number of articles.)**
      
#### Grammar Checks
- [x] Have you spellchecked and grammar checked your article? - **Tools:** [Write&Improve](https://writeandimprove.com/?lang=en-GB) - [ProWritingAid](https://prowritingaid.com/) -  [Grammarly](https://grammarly.com) 
- [x] Have you checked your article for readability? - **Tool:** [Hemmingway](http://www.hemingwayapp.com)
- [x] Have you added sources for quotes and images that aren't yours?

#### Technical Checks
- [x] Are your code snippets properly formatted for syntax highlighting - **see [Syntax guide](https://gohugo.io/content-management/syntax-highlighting)**

### Contribution Guidelines
For first-time contributors and for more details, **see [Contributing Guidelines](https://github.com/section-io/engineering-education/blob/master/CONTRIBUTING.md)**

### CODE REVIEW

**Comment by lalith1403** [comment]
Well done on a well-written article. A few suggestions. Use headers H3 and beyond. Avoid repetition of phrases, like you use level like manner many times. Think of ways where the text does not feel redundant. Make the change, and this should be ready for the final round of review.

**Comment by lalith1403** [comment]
Also, while pushing the changes, don't fork the repository again. Just switch to this branch, perform the pull command, and then add the files, commit the changes, and push it to the same branch. 
The commands are:
`git switch master` (you will probably be in master, already. It is wise to create new branches for new articles and leave the master branch unaltered)
`git pull `
`git add .`
`git commit -m "made some changes"`
`git push`

**Comment by lalith1403** [comment]
Let me know if you have any doubts about git commands.

**Comment by hectorkambow** [comment]
Is this a duplicate of #754 ??

**Comment by tensoncai** [comment]
Yes but you can ignore #754 and merge the #937 branch.

Sorry and thanks!
Tenson

**Comment by hectorkambow** [comment]
Good morning/afternoon @tensoncai  👋  - getting your article ready for a final review - since this is your 1st article - if you could please include a short bio and headshot to include toward the bottom of all your articles. 
Please see any example in the author folder in the repo as a guide 🚀  
Thank you

**Comment by tensoncai** [comment]
It’s done. Thank you!

Tenson

**Pull request merged**
