### PR TITLE
How to use Nmap to scan networks

### PR DESCRIPTION
**Pull request by damikanye**
#### Preliminary Checks - Formatting and Structure 
- [x] Does your article follow any of the suggested structure formats? - **see [example formats](https://github.com/section-io/engineering-education/blob/master/CONTRIBUTING.md#example-format-structure)**
- [x] Is your article properly formatted in Markdown? - **see [Github Markdown guide](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet)**
- [x] Have you used the correct folder and file structure? - **see [Contribution Guidelines](https://github.com/section-io/engineering-education/blob/master/CONTRIBUTING.md)**
- [x] Is your article over 750 words? - **Tool**: [Wordcounter.net](https://wordcounter.net)
- [x] Have you used our preferred heading structure? - **[H3 (###) and up](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet#headers)**
- [x] Does your article provide enough value and detail about your topic? - **Articles should be clear, accurate, and fully explained.**
- [x] Can your article be understood by beginners? - **Assume the audience is smart but has no prior exposure to the common terminology in your article.**
- [x] Have you included a hero image that is 600x400 pixels and have the copyright to use it? - **Tools:** [Pixlr Image Editor](https://pixlr.com/e) for resizing and [Unsplash](https://unsplash.com) for Creative Commons images
- [x] In your PR - add a comment that states **["This fixes #(enter your Idea Content Form #)"](https://youtu.be/TKJ4RdhyB5Y?t=278)** to link and close your Idea Content (issue) when the PR is merged.
      

#### Grammar Checks
- [x] Have you spellchecked and grammar checked your article? - **Tool:** [Grammarly](https://grammarly.com)
- [x] Have you checked your article for readability? - **Tool:** [Hemmingway](http://www.hemingwayapp.com)
- [ ] Have you added sources for quotes and images that aren't yours?

#### Technical Checks
- [ ] Are your code snippets properly formatted for syntax highlighting - **see [Syntax guide](https://gohugo.io/content-management/syntax-highlighting)**

### Contribution Guidelines
For first-time contributors and for more details, **see [Contributing Guidelines](https://github.com/section-io/engineering-education/blob/master/CONTRIBUTING.md)**

### CODE REVIEW

**Comment by damikanye** [comment]
Fixes #486

**Comment by hectorkambow** [comment]
Plagiarism  Check (see PDF)
@damikanye 
Thank you for submitting your Nmap article - upon pushing your article through our 3rd party plagiarism checker it raised a quite a few flags - and the % is very high. 
Please review the article and be sure we are using original and unique content when approaching our topics - we do not want to be simply changing words to re-explain a previously explored topic. 
🚀 
Thank you 

(The code should be fine - but let's
[Uploading How to use Nmap to scan networks #581.pdf…]()
 go over the intro to be sure) 👍

**Comment by hectorkambow** [comment]
Lets also be sure we are providing the audience with enough explanation of what is going on with the code example (I'm just quickly looking at the article - have yet to jump in) 👍

**Comment by damikanye** [comment]
Hello @

> Plagiarism Check (see PDF)
> @damikanye
> Thank you for submitting your Nmap article - upon pushing your article through our 3rd party plagiarism checker it raised a quite a few flags - and the % is very high.
> Please review the article and be sure we are using original and unique content when approaching our topics - we do not want to be simply changing words to re-explain a previously explored topic.
> 🚀
> Thank you
> 
> (The code should be fine - but let's
> Uploading How to use Nmap to scan networks #581.pdf…
> go over the intro to be sure) 👍

Can't see any PDF attached.

**Comment by hectorkambow** [comment]
Following up from my comment on Slack. 
Closing PR 
image

**Pull request closed without merging**
