### PR TITLE
Uploading Multipart/Form-data using Multer in a node.js application.

### PR DESCRIPTION
**Pull request by sardug10**
#### Preliminary Checks - Formatting and Structure 
- [x] Does your article follow any of the suggested structure formats? - **see [example formats](https://github.com/section-io/engineering-education/blob/master/CONTRIBUTING.md#example-format-structure)**
- [x] Is your article properly formatted in Markdown? - **see [Github Markdown guide](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet)**
- [x] Have you used the correct folder and file structure? - **see [Contribution Guidelines](https://github.com/section-io/engineering-education/blob/master/CONTRIBUTING.md)**
- [x] Is your article over 750 words? - **Tool**: [Wordcounter.net](https://wordcounter.net)
- [x] Have you used our preferred heading structure? - **[H3 (###) and up](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet#headers)**
- [x] Does your article provide enough value and detail about your topic? - **Articles should be clear, accurate, and fully explained.**
- [x] Can your article be understood by beginners? - **Assume the audience is smart but has no prior exposure to the common terminology in your article.**
- [x] Have you included a hero image that is 600x400 pixels and have the copyright to use it? - **Tools:** [Pixlr Image Editor](https://pixlr.com/e) for resizing and [Unsplash](https://unsplash.com) for Creative Commons images
- [x] In your PR - add a comment that states **["This fixes #(enter your Idea Content Form #)"](https://youtu.be/TKJ4RdhyB5Y?t=278)** to link and close your Idea Content (issue) when the PR is merged.

**NOTE: (1st time contributors - submit ONLY one article to get familiar with the process and style-once published, you can then submit any number of articles.)**
      
#### Grammar Checks
- [x] Have you spellchecked and grammar checked your article? - **Tools:** [Write&Improve](https://writeandimprove.com/?lang=en-GB) - [ProWritingAid](https://prowritingaid.com/) -  [Grammarly](https://grammarly.com) 
- [x] Have you checked your article for readability? - **Tool:** [Hemmingway](http://www.hemingwayapp.com)
- [x] Have you added sources for quotes and images that aren't yours?

#### Technical Checks
- [x] Are your code snippets properly formatted for syntax highlighting - **see [Syntax guide](https://gohugo.io/content-management/syntax-highlighting)**

### Contribution Guidelines
For first-time contributors and for more details, **see [Contributing Guidelines](https://github.com/section-io/engineering-education/blob/master/CONTRIBUTING.md)**

### CODE REVIEW

**Comment by hectorkambow** [comment]
@sardug10  
FYI 
Lets be sure to include the issue # that this PR is tied to. You can click on the right hand side under "Linked Issues" to connect the issue to the PR. 👍 

"In your PR - add a comment that states "This fixes #(enter your Idea Content Form #)" to link and close your Idea Content (issue) when the PR is merged." 

This fixed #1133

**Comment by sardug10** [comment]
This fixes [#1133 ](https://github.com/section-io/engineering-education/issues/1035)

**Review by kayere — APPROVED** [review]
Hello @sardug10, this is a very informative article. However, I'd suggest you improve your grammar. Also, minimize the number of bold sentences in your upcoming articles; They don't really add any value. Check my prelim review commit to view the changes I made and apply them in your future articles.

**Comment by sardug10** [comment]
> Hello @sardug10, this is a very informative article. However, I'd suggest you improve your grammar. Also, minimize the number of bold sentences in your upcoming articles; They don't really add any value. Check my prelim review commit to view the changes I made and apply them in your future articles.

Hello @kayere To be honest, I used Grammarly and Hemmingway for writing each of my sentences, so I don't really know where the grammar part went wrong. Also, Thank you for reviewing it so well. I will definitely consider your reviews for my future articles.

**Review by louisefindlay23 — APPROVED** [review]
This article is ready for publication, @hectorkambow.

**Comment by hectorkambow** [comment]
@sardug10 Great article - seems very informative and helpful. 

Please be sure to go over the minute details I changed just to help it flow better. 

One thing I would suggest off the bat - is to be mindful with the word finally - do not overuse it 👍 

Other small minor things - but that would truly help speed up future articles and improve overall quality.

cc: @kayere 

cc: @louisefindlay23

**Comment by hectorkambow** [comment]
plagiarism check done

**Comment by sardug10** [comment]
This Fixed [#1035](https://github.com/section-io/engineering-education/issues/1035)

**Pull request merged**
