### PR TITLE
Functional Programming with Haskell 

### LINKED ISSUE #1093: Functional Programming with Haskell
### Brief Summary: 
Describe the what, why, and how of your content idea in 2-5 sentences.
This article introduces Haskell, which is a functional programming language. Characteristics that make Haskell unique will be discussed. There will be some examples to get the reader to solve a few basic problems with functional programming.
### Key Takeaways: 
What are the 3-5 most important things the reader should understand or be able to do after reading this article?
1. Ability to define the difference between functional and imperative programming. 
2. Write basic functions involving lists and tuples in Haskell. 
3. Understand why Haskell is famous for "lazy" computations and how it affects function argument evaluation.

### References: 
Please list links to any published content/research that you intend to use to support/guide this article. (If none, please indicate 'N/A'.)
Learn You a Haskell for Greater Good (available at http://learnyouahaskell.com/)

### PR DESCRIPTION
**Pull request by nimra200**
This fixes #1093
Article description: 
There are many functional programming languages and Haskell is one of them. This article covers some aspects of functional programming with Haskell. It assumes that you are familiar with lists, functions, loops and recursion. 

#### Preliminary Checks - Formatting and Structure 
- [x] Does your article follow any of the suggested structure formats? - **see [example formats](https://github.com/section-io/engineering-education/blob/master/CONTRIBUTING.md#example-format-structure)**
- [x] Is your article properly formatted in Markdown? - **see [Github Markdown guide](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet)**
- [x] Have you used the correct folder and file structure? - **see [Contribution Guidelines](https://github.com/section-io/engineering-education/blob/master/CONTRIBUTING.md)**
- [x] Is your article over 750 words? - **Tool**: [Wordcounter.net](https://wordcounter.net)
- [x] Have you used our preferred heading structure? - **[H3 (###) and up](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet#headers)**
- [x] Does your article provide enough value and detail about your topic? - **Articles should be clear, accurate, and fully explained.**
- [x] Can your article be understood by beginners? - **Assume the audience is smart but has no prior exposure to the common terminology in your article.**
- [x] Have you included a hero image that is 600x400 pixels and have the copyright to use it? - **Tools:** [Pixlr Image Editor](https://pixlr.com/e) for resizing and [Unsplash](https://unsplash.com) for Creative Commons images
- [x] In your PR - add a comment that states **["This fixes #(enter your Idea Content Form #)"](https://youtu.be/TKJ4RdhyB5Y?t=278)** to link and close your Idea Content (issue) when the PR is merged.

**NOTE: (1st time contributors - submit ONLY one article to get familiar with the process and style-once published, you can then submit any number of articles.)**
      
#### Grammar Checks
- [x] Have you spellchecked and grammar checked your article? - **Tools:** [Write&Improve](https://writeandimprove.com/?lang=en-GB) - [ProWritingAid](https://prowritingaid.com/) -  [Grammarly](https://grammarly.com) 
- [x] Have you checked your article for readability? - **Tool:** [Hemmingway](http://www.hemingwayapp.com)
- [x] Have you added sources for quotes and images that aren't yours?

#### Technical Checks
- [x] Are your code snippets properly formatted for syntax highlighting - **see [Syntax guide](https://gohugo.io/content-management/syntax-highlighting)**

### Contribution Guidelines
For first-time contributors and for more details, **see [Contributing Guidelines](https://github.com/section-io/engineering-education/blob/master/CONTRIBUTING.md)**

### CODE REVIEW

**Review by lalith1403 — CHANGES_REQUESTED** [review]
Use H3 (###) headers and beyond in your article. I have changed it in this article. However, since this introduces Haskell and functional programming, give examples of projects using these concepts. As a reader, where would I be encouraged to use this? 

The current content is well written and grammatically correct. However, adding additional information will ensure the reader gets a deeper interest in Haskell.

**Comment by nimra200** [comment]
Thanks for the feedback. I've added real-life examples of Haskell being used, and reasons why the reader should use concepts I discussed.

**Comment by lalith1403** [comment]
Can you add a hero image. Refer to the articles present in the article folder in the main repository for more details.

**Comment by nimra200** [comment]
Hero image added.

**Comment by hectorkambow** [comment]
plagiarism check done

**Pull request merged**
