### PR TITLE
Add Python Data Structures, Part 2 & Part 3

### PR DESCRIPTION
**Pull request by cyberShaw**
I've added the second part in the series of Python Data Structures!

### CODE REVIEW

**Comment by cyberShaw** [comment]
Have added another article to this! This one is Part 3 in the Data Structures series in Python.
It deals with the implementation, application of stacks in Python. I've added it as a commit in this PR.

**Comment by hectorkambow** [comment]
Thank you @cyberShaw  - please ensure you ran your article through the 
http://www.hemingwayapp.com/

to help with run-on sentences - grammar, formatting, and word count as well 👍 

(if you haven't already)

**Comment by cyberShaw** [comment]
> Thank you @cyberShaw - please ensure you ran your article through the
> http://www.hemingwayapp.com/
> 
> to help with run-on sentences - grammar, formatting, and word count as well 👍
> 
> (if you haven't already)

I just ran a check through the website, and the sentences marked as 'Hard to Read' are all technical sentences like, 
"When the function is called, an activation record is created for it and keeps track of parameters and information like local variables, return address, static and dynamic links and the return value."

So these sentences can't really be changed. But formatting, grammar turned out to be perfect with no issues 👍

**Comment by hectorkambow** [comment]
@cyberShaw Fantastic - this looks great - upon a quick glance - 

Wanted to ask if you could consolidate part 2 & 3 we prefer to have complete articles when it comes to tutorials on how to build something. It would be frustrating for somebody to get to the end of this article to simply have to click on to the next. Moving forward tutorials should be complete the objectives in their entirety. (Or as complete as they can be - if they need to be or can be created to be stand along article then splitting them is fine) 🚀

**Comment by cyberShaw** [comment]
That's a very valid point that you've put forth. But I've structured this
series such that each article is an independent one.
Every article deals with a data structure in python and they're completely
independent of each other. Merging the articles might be a little bit too
much for a beginner to python since it would be too much information for a
single article :D

**Comment by hectorkambow** [comment]
Thank you that makes sense - sounds good. 

In regards to part 2 & 3 can you submit each on a separate branch to be reviewed independently  👍 

https://github.com/section-io/engineering-education/blob/master/UPLOAD_INSTRUCTIONS.md

**Comment by cyberShaw** [comment]
@hectorkambow Closing this PR to open new ones for the articles!

**Pull request closed without merging**
