### PR TITLE
Cloud firestore

### PR DESCRIPTION
**Pull request by LinusMuema**
This is a short article that shows developers how Cloud Firestore works and some of its basic operations.

### CODE REVIEW

**Comment by hectorkambow** [comment]
Just finished up doing a preliminary review on your Firestore article 🚀  
Very informative article - learned a lot about Firestore - but I think there is an opportunity to add some value for the audience. 

As I'm reading the article - I learn a lot about Firestore - but little as to why I am learning about it - you did a fantastic job explaining the code and the functions - but as a reader, I'm left asking when can I use this - why would I use this - why did you use this - the examples given serve great to showcase getting started with Firestore (but that is something the reader may be able to get from looking at the official documentation).

We want to craft our articles with a problem-solution perspective - what problem does this article solve for the reader - what awesome solution(s) are we sharing. 

Overall - I think the article is great - just suggesting how we could improve this one (and in general moving forward) 

Hope this helps 🚀

**Comment by hectorkambow** [comment]
Also (sidenote) the hero images need to be from a free to use site like unspalsh - just double checking for the hero image - since I saw it had the logo. 🤔

**Comment by LinusMuema** [comment]
Okay. I will add more about why we are using it.

**Comment by hectorkambow** [comment]
👋  Good afternoon Molly - wanted to ask if you could give this Cloud Firestore a tech review before we publish. 
Gave it a preliminary review. 🚀 
Thank you

**Review by ninjaginja — COMMENTED** [review]
I feel like the Cloud Firestore vs Realtime Database section should be the first section of the article, rather than the last. You refer to comparisons with realtime databases throughout the article, but you don't define it until the end. I think defining it upfront would help readers better understand the granular differences as they're reading through.

**Comment by hectorkambow** [comment]
@LinusMuema - please see the input from our tech reviewer Molly - she has some great feedback on the flow of the article.  🚀

**Pull request merged**
