### PR TITLE
Article: Machine learning on edge with r pi and tf lite

### PR DESCRIPTION
**Pull request by rohanreddych**

### CODE REVIEW

**Comment by rohanreddych** [comment]
@hectorkambow added image credits and made some minor grammatical changes I hope this is the correct format

**Comment by hectorkambow** [comment]
Good afternoon @calvinbrewer  - could you please give this article a tech review when you are free, please. & Thank you 🚀

**Comment by rohanreddych** [comment]
@kurt-sectionio I want to add how to train a model with TF2 and convert it to tflite, but I think it will become *too* big so should I make a separate gist for it. I also made some edits: moved the applications up, added comments to `get_output` to describe why they are used. Added more content, please give feedback.

**Comment by hectorkambow** [comment]
> I want to add how to train a model with TF2 and convert it to tflite, but I think it will become _too_ big so should I make a separate gist for it. I also made some edits: moved the applications up, added comments to `get_output` to describe why they are used. Added more content, please give feedback.

@rohanreddych  - if it's a useful model to add to the article - go for it - any added value for the audience is always helpful 🚀

The article getting too big is not a concern - we always lean towards the side of having a complete idea for others to reference.

**Comment by rohanreddych** [comment]
Hello @kurt-sectionio 
> Can TFLite handle RNNs?

Yes! they can applications like [smart reply](https://github.com/tensorflow/examples/tree/master/lite/examples/smart_reply/android) which use RNNs are supported by TF lite.

**Comment by kurt-sectionio** [comment]
Cool. So can any TF2 model be converted to TFLite? I'm just trying to think of tidbits you can share that will be helpful to a newbie reader.

**Comment by rohanreddych** [comment]
> Cool. So can any TF2 model be converted to TFLite? I'm just trying to think of tidbits you can share that will be helpful to a newbie reader.

Added some information regarding this

> In line 131 you assign np.array(img) to input_data. Then in line 133 you expand_dims (img, ...). Don't you want to run that on input_data?

Yes, my bad. Made changes. @kurt-sectionio can you give a final review?

**Pull request merged**
