### PR TITLE
How to create CRUD API using Spring Boot

### LINKED ISSUE #845: How to create CRUD API with Spring MVC
### Brief Summary: 
Spring Boot is an open source Java-based framework that makes it easy to create stand-alone, production-grade Spring based Applications that you can "just run".
This article aims to teach the reader how to create various crud APIS with Spring boot and Spring MVC.

### Key Takeaways: 
Basic [Spring Boot](https://spring.io/guides/gs/spring-boot/) knowledge is required to understand the concept covered in this article.
1. What is Spring Boot and Spring MVC.
2. Basics of Spring MVC.
3. How to create crud API Spring MVC.
4. Basics of Spring Data JPA. 
5. Using H2 database for data persistence.

### References: 
[Spring Data JPA](https://spring.io/projects/spring-data-jpa)

### PR DESCRIPTION
**Pull request by paulodhiambo**
#### Preliminary Checks - Formatting and Structure 
- [x] Does your article follow any of the suggested structure formats? - **see [example formats](https://github.com/section-io/engineering-education/blob/master/CONTRIBUTING.md#example-format-structure)**
- [x] Is your article properly formatted in Markdown? - **see [Github Markdown guide](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet)**
- [x] Have you used the correct folder and file structure? - **see [Contribution Guidelines](https://github.com/section-io/engineering-education/blob/master/CONTRIBUTING.md)**
- [x] Is your article over 750 words? - **Tool**: [Wordcounter.net](https://wordcounter.net)
- [x] Have you used our preferred heading structure? - **[H3 (###) and up](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet#headers)**
- [x] Does your article provide enough value and detail about your topic? - **Articles should be clear, accurate, and fully explained.**
- [x] Can your article be understood by beginners? - **Assume the audience is smart but has no prior exposure to the common terminology in your article.**
- [x] Have you included a hero image that is 600x400 pixels and have the copyright to use it? - **Tools:** [Pixlr Image Editor](https://pixlr.com/e) for resizing and [Unsplash](https://unsplash.com) for Creative Commons images
- [x] In your PR - add a comment that states **["This fixes #(enter your Idea Content Form #)"](https://youtu.be/TKJ4RdhyB5Y?t=278)** to link and close your Idea Content (issue) when the PR is merged.

**NOTE: (1st time contributors - submit ONLY one article to get familiar with the process and style-once published, you can then submit any number of articles.)**
      
#### Grammar Checks
- [x] Have you spellchecked and grammar checked your article? - **Tools:** [Write&Improve](https://writeandimprove.com/?lang=en-GB) - [ProWritingAid](https://prowritingaid.com/) -  [Grammarly](https://grammarly.com) 
- [x] Have you checked your article for readability? - **Tool:** [Hemmingway](http://www.hemingwayapp.com)
- [x] Have you added sources for quotes and images that aren't yours?

#### Technical Checks
- [x] Are your code snippets properly formatted for syntax highlighting - **see [Syntax guide](https://gohugo.io/content-management/syntax-highlighting)**

### Contribution Guidelines
For first-time contributors and for more details, **see [Contributing Guidelines](https://github.com/section-io/engineering-education/blob/master/CONTRIBUTING.md)**

This fixes #845

### CODE REVIEW

**Comment by paulodhiambo** [comment]
This fixes #845

**Comment by hectorkambow** [comment]
👋 Thank you for submitting this PR - we will review it ASAP - all PRs go into our queue will be looked over before being approved to be published.

**Review by LinusMuema — APPROVED** [review]
@paulodhiambo 
This article is amazing and really informative. Just one pointer: make use of the tutorial template for ease of following through i.e step 1, step 2 etc.

But everything else checks out. Awesome job!

@hectorkambow you could give this article a final review.

**Comment by hectorkambow** [comment]
plagiarism check done

**Comment by hectorkambow** [comment]
@paulodhiambo Great job - very nice tutorial - be sure to see my final commits for some minor changes I made. 

🚀  
cc @LinusMuema

**Pull request merged**
