### PR TITLE
Getting to Grips with APIs: Authentication

### PR DESCRIPTION
**Pull request by hectorkambow**
Duplicate of [this PR](https://github.com/section-io/engineering-education/pull/243/files?short_path=d2245ee#diff-d2245eef40948a02ba811ac3a24747dd) - to clean older commits 
adding .md file
adding hero image

### CODE REVIEW

**Comment by hectorkambow** [comment]
Good afternoon @AskAlice 👋  - wanted to ask if you could give this API article a tech review before we publish whenever you have a moment 🚀  
Thank you

**Comment by louisefindlay23** [comment]
@askalice, added a screenshot of the Owned Books page. Were you referring to the HTML code itself?

**Comment by AskAlice** [comment]
Lgtm @hectorkambow please merge @louisefindlay23's changes into this branch then merge the pr

**Comment by louisefindlay23** [comment]
@hectorkambow, with contributor access I can merge the branches if that's easier for you.

**Pull request merged**
