### PR TITLE
Basics of Routing

### PR DESCRIPTION
**Pull request by Taiwrash**
### Article Checklist
**NOTE: (1st time contributors - submit ONLY one article to get familiar with the process, quality, and style-once published, you can then submit any number of articles.)**
#### Preliminary Checks - Formatting and Structure 
- [x] Does your article follow any of the suggested structure formats? - **see [example formats](https://github.com/section-io/engineering-education/blob/master/CONTRIBUTING.md#example-format-structure)**
- [x] Is your article properly formatted in Markdown? - **see [Github Markdown guide](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet)**
- [x] Have you used the correct folder and file structure? - **see [Contribution Guidelines](https://github.com/section-io/engineering-education/blob/master/CONTRIBUTING.md)**
- [x] Is your article over 750 words? - **Tool**: [Wordcounter.net](https://wordcounter.net)
- [x] Have you used our preferred heading structure? - **[H3 (###) and up](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet#headers)**
- [x] Does your article provide enough value and detail about your topic? - **Articles should be clear, accurate, and fully explained.**
- [x] Can your article be understood by beginners? - **Assume the audience is smart but has no prior exposure to the common terminology in your article.**
- [x] Have you included a hero image that is 600x400 pixels and have the copyright to use it? - **Tools:** [Pixlr Image Editor](https://pixlr.com/e) for resizing and [Unsplash](https://unsplash.com) for Creative Commons images
- [ ] In your PR - add a comment that states **["This fixes #(enter your Idea Content Form #)"](https://youtu.be/TKJ4RdhyB5Y?t=278)** to link and close your Idea Content (issue) when the PR is merged.
      
#### Grammar Checks
- [x] Have you spellchecked and grammar checked your article? - **Tools:** [Write&Improve](https://writeandimprove.com/?lang=en-GB) - [ProWritingAid](https://prowritingaid.com/) -  [Grammarly](https://grammarly.com) 
- [x] Have you checked your article for readability? - **Tool:** [Hemmingway](http://www.hemingwayapp.com)
- [ ] Have you added sources for quotes and images that aren't yours?

#### Technical Checks
- [x] Are your code snippets properly formatted for syntax highlighting - **see [Syntax guide](https://gohugo.io/content-management/syntax-highlighting)**

### Contribution Guidelines
For first-time contributors and for more details, **see [Contributing Guidelines](https://github.com/section-io/engineering-education/blob/master/CONTRIBUTING.md)**

### CODE REVIEW

**Comment by hectorkambow** [comment]
@Taiwrash  What issue number (approved topic form) does this PR tie into ?

cc @lalith1403

**Comment by Taiwrash** [comment]
### No issue was created for this topic
@hectorkambow there is no special issue created for this, I worked based on the suggestion of topics I got in my email after my application sir. And when I was reading the instructions I didn't notice the part that I need to create an issue, I am really sorry for an issue or inconveniences caused! @lalith1403 .

- kindly help me out on the next step
- let me know what to do next
- thanks, I will be grateful for your supports.

**Comment by Taiwrash** [comment]
### No issue was created for this topic
@hectorkambow there is no special issue created for this, I worked based on the suggestion of topics I got in my email after my application sir. And when I was reading the instructions I didn't notice the part that I need to create an issue, I am really sorry for an issue or inconveniences caused! @lalith1403 .

- kindly help me out on the next step
- let me know what to do next
- thanks, I will be grateful for your supports.

**Comment by lalith1403** [comment]
Create an issue. Go to the issue section under the eng-ed repository, and click on create a new issue. Select the content form template and proceed. Once done, submit the issue. 

The issue is then approved or rejected on the basis of the validity of the idea proposed. Then you may proceed with the PR. For now I will close this PR.

**Comment by hectorkambow** [comment]
@Taiwrash 
No problem - the reason for this is to help avoid any topic overlap with past published articles or current PR (new articles) in the queue. 

I saw you created a new issue - which is great 👍 

Currently, we are experiencing a high volume of PRs and have put a 2 week pause on accepting new articles. 

Due to this and the fact that the PR was not approved already - we may be closing this PR - in the mean time we encourage you to get familiar with the process. 

We have [created this folder ](https://github.com/section-io/engineering-education/tree/master/new_contributors)and put together this [resources page](https://github.com/section-io/engineering-education/blob/master/new_contributors/resources-page.md) to help guide any new contributor. 

Please join the [Slack channel](https://join.slack.com/t/sectionio-community/shared_invite/zt-6174cklt-YFpHmQIAUmc927jqN2EIZQ) to see what the community is talking about and what new exciting changes are coming to the EngEd community as a whole. 
Thank you 🚀  
We are happy to have you join.

**Pull request closed without merging**
