### PR TITLE
Relevancy of Quantum Cryptography - Cluster Algorithms

### PR DESCRIPTION
**Pull request by josborne891**

### CODE REVIEW

**Comment by josborne891** [comment]
Adding the "Basics of Cluster Algorithms"

**Comment by ninjaginja** [comment]
Hey @josborne891, thanks for your continued work on this article. Our technical review committee had a few more suggestions/edits for you before we push this to production:

> It might be worth putting in a line or two describing how clustering is unsupervised learning, as opposed to supervised learning. In fact, clustering is the go-to class of algorithms for unsupervised learning. Probably good search hits for "unsupervised learning", etc.
> 
> Line 20: Author introduces "similarities" and "proximity" but then moves on. I would like to see a few lines about proximity. Maybe end the sentence at "similarities" and then add a sentence like: Computationally, we describe similarity by measures of proximity ...."
> 
> Line 44: "... is not linear, rather it is quadratic." --could be: "... is quadratic rather than linear."

**Comment by josborne891** [comment]
@ninjaginja the changes have been made to the repository and is ready for review

**Comment by hectorkambow** [comment]
@josborne891 if I'm not mistaken - this is a batch of newer suggestions. (other than the revision(s) I had suggested in Slack 👍 

In the starting paragraph, you start by introducing the reader to terms like "similarities" and "proximity" - please elaborate.

It might be worth putting in a line or two describing how clustering is unsupervised learning, as opposed to supervised learning. In fact, clustering is the go-to class of algorithms for unsupervised learning. Probably good search hits for "unsupervised learning", etc.

**Comment by josborne891** [comment]
> @josborne891 if I'm not mistaken - this is a batch of newer suggestions. (other than the revision(s) I had suggested in Slack 👍
> 
> In the starting paragraph, you start by introducing the reader to terms like "similarities" and "proximity" - please elaborate.
> 
> It might be worth putting in a line or two describing how clustering is unsupervised learning, as opposed to supervised learning. In fact, clustering is the go-to class of algorithms for unsupervised learning. Probably good search hits for "unsupervised learning", etc.

**Comment by josborne891** [comment]
I have made several changes to the grammar to make it sound better and hope it is satisfactory. Let me know of any more changes you wish to add.

**Comment by hectorkambow** [comment]
migrated to [pr89](https://github.com/section-io/engineering-education/pull/89)

**Pull request closed without merging**
