### PR TITLE
Building a python package and publishing on PyPI

### PR DESCRIPTION
**Pull request by jamessandy**
#### Preliminary Checks - Formatting and Structure 
- [x] Does your article follow any of the suggested structure formats? - **see [example formats](https://github.com/section-io/engineering-education/blob/master/CONTRIBUTING.md#example-format-structure)**
- [x] Is your article properly formatted in Markdown? - **see [Github Markdown guide](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet)**
- [x] Have you used the correct folder and file structure? - **see [Contribution Guidelines](https://github.com/section-io/engineering-education/blob/master/CONTRIBUTING.md)**
- [x] Is your article over 750 words? - **Tool**: [Wordcounter.net](https://wordcounter.net)
- [x] Have you used our preferred heading structure? - **[H3 (###) and up](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet#headers)**
- [x] Does your article provide enough value and detail about your topic? - **Articles should be clear, accurate, and fully explained.**
- [x] Can your article be understood by beginners? - **Assume the audience is smart but has no prior exposure to the common terminology in your article.**
- [x] Have you included a hero image that is 600x400 pixels and have the copyright to use it? - **Tools:** [Pixlr Image Editor](https://pixlr.com/e) for resizing and [Unsplash](https://unsplash.com) for Creative Commons images
- [x] In your PR - add a comment that states **["This fixes #(enter your Idea Content Form #)"](https://youtu.be/TKJ4RdhyB5Y?t=278)** to link and close your Idea Content (issue) when the PR is merged.
      

#### Grammar Checks
- [x] Have you spellchecked and grammar checked your article? - **Tool:** [Grammarly](https://grammarly.com)
- [x] Have you checked your article for readability? - **Tool:** [Hemmingway](http://www.hemingwayapp.com)
- [x] Have you added sources for quotes and images that aren't yours?

#### Technical Checks
- [x] Are your code snippets properly formatted for syntax highlighting - **see [Syntax guide](https://gohugo.io/content-management/syntax-highlighting)**

### Contribution Guidelines
For first-time contributors and for more details, **see [Contributing Guidelines](https://github.com/section-io/engineering-education/blob/master/CONTRIBUTING.md)**

### CODE REVIEW

**Comment by jamessandy** [comment]
This fixes #475

**Comment by lalith1403** [comment]
A few initial fixes:

1. Rename the img.jpg as hero.jpg. It's a naming convention and helps maintain uniformity.
2. Add a short bio and headshot under a folder named your name in the author directory. The author folder is present in the main repository.

**Comment by hectorkambow** [comment]
plagiarism check done

**Comment by jamessandy** [comment]
Can't find a folder with my name @lalith1403

**Comment by hectorkambow** [comment]
> Can't find a folder with my name @lalith1403

Correct- (if you're a 1st time contributor) you need to make your author folder - in the forked Repo on you local - duplicate one of the author folders replace the avatar image. bio. and name. 
🚀 
Hope that helps @jamessandy

**Comment by jamessandy** [comment]
Done @lalith1403

**Comment by hectorkambow** [comment]
@jamessandy 
Please watch this short video - these type of videos really helped me a lot when I started to learn about GitHub flows:
https://www.youtube.com/watch?v=nT8KGYVurIU&t=47s

**Comment by hectorkambow** [comment]
This PR now has merge conflicts (see image) 
I believe you need to rebase your Forked Repo - 
image

**Comment by hectorkambow** [comment]
>then use this every time before contributing a new article to keep it up to date
git fetch section

git pull --rebase section master

git push origin

**Comment by jamessandy** [comment]
fixed

**Comment by hectorkambow** [comment]
While we did clean the merge conflict 🎉 @jamessandy 
It seems we also committed past articles and PRs into the files. 
The best option would be to close this PR and submit a new one with just your article. 
(see image)
image

**Pull request closed without merging**
