### PR TITLE
Introduction to Generative Adversarial Networks

### PR DESCRIPTION
**Pull request by adithbharadwaj**
Requesting the team to review my article on GANs. This article introduces the readers to the basics of GANs, where and why they are used, how they are built, etc. It also explores the architecture of a simple GAN and the system flow.

### CODE REVIEW

**Comment by hectorkambow** [comment]
Good afternoon 👋 Pavel @pavelnikolov 🚀 - wanted to ask if you could give this article a tech review before we publish - whenever you have a moment.
Thank you

**Comment by hectorkambow** [comment]
Good afternoon Ivan  @ivan-section-io  👋 - I wanted to ask if you could give this Generative Adversarial Networks article a tech review when you have a moment. 
Thank you 🚀

**Comment by ivan-section-io** [comment]
LGTM

**Comment by hectorkambow** [comment]
Good evening @adithbharadwaj  - getting ready to publish your article - but wanted to draw attention on a couple of sentences - that were red flagged by our plagiarism checker:
(see image) 
If you could change those sentences to something a bit more original. 
Thank you 🚀 
image

**Comment by adithbharadwaj** [comment]
> Good evening @adithbharadwaj - getting ready to publish your article - but wanted to draw attention on a couple of sentences - that were red flagged by our plagiarism checker:
> (see image)
> If you could change those sentences to something a bit more original.
> Thank you rocket
> image

Good morning @hectorkambow . I have made the changes you requested. Please verify and tell me if there is anything I can do.

**Pull request merged**
