### PR TITLE
Feature engineering in machine learning: An Overview

### LINKED ISSUE #340: Feature Engineering in Machine Learning: An Overview
# Brief Summary

Describe the what, why, and how of your content idea in 2-5 sentences.

The features used in a machine learning model are often the difference between model success and failure. Therefore, it is not enough building models but making sure they offer the best possible performance. The process of feature engineering ensures.

# Key Takeaways:

What are the 3-5 most important things the reader should understand or be able to do after reading this article?

1. Understand the need/ importance of feature engineering in ML
2. Explore a few types of data, features, and processes
3. Differentiate between feature selection and feature engineering
4. Compare automated and manual feature engineering

# References

Please list links to any published content/research that you intend to use to support/guide this article. (If none, please indicate 'N/A'.)

1. [Feature engineering for detecting spammers on Twitter: Modelling and analysis](https://doi.org/10.1177%2F0165551516684296)

2. [Feature selection for classification: A review](http://eprints.kku.edu.sa/170/1/feature_selection_for_classification.pdf)

3. [Benchmarking automatic machine learning frameworks](https://arxiv.org/pdf/1808.06492v1.pdf)

4. [Feature Engineering in Python](https://towardsdatascience.com/feature-engineering-in-python-part-i-the-most-powerful-way-of-dealing-with-data-8e2447e7c69e)

5. [Feature Engineering Techniques](https://towardsdatascience.com/feature-engineering-techniques-9a57e4901545)

6. [Create Features](https://docs.microsoft.com/en-us/azure/machine-learning/team-data-science-process/create-features)

7. [Feature Engineering: What powers machine learning](https://towardsdatascience.com/feature-engineering-what-powers-machine-learning-93ab191bcc2d)

8. [A practical guid to Feature Engineering in Python](https://heartbeat.fritz.ai/a-practical-guide-to-feature-engineering-in-python-8326e40747c8)

### PR DESCRIPTION
**Pull request by collins-a**
Wrote an article on Feature engineering in machine learning.

Contains hero image as hero.jpg 
Has index.md file

This fixes #340

### CODE REVIEW

**Comment by hectorkambow** [comment]
Plagiarism check done

**Comment by hectorkambow** [comment]
👋  @collins-a 
I was trying to review your article - but noticed this error again - not sure if it was something I did - my text editor was "showing" I needed to push - but I had no saved changes on my local - not sure how. But I tried to force push to clear the message.

If you could try a rebase to see if that will clear up this message (see attached) 
Thank you 
image

**Comment by collins-a** [comment]
Hey @hectorkambow. Thanks for the heads up. Let me try fixing it ASAP

**Comment by collins-a** [comment]
@hectorkambow I hope it's fixed now. Also hope I didn't undo your good work with the editing

**Comment by hectorkambow** [comment]
Not sure why I am seeing this error message when I try to checkout your article in my Atom:
image

**Comment by hectorkambow** [comment]
When I try to pull:
image

**Comment by hectorkambow** [comment]
It may be easier to submit another PR - transferring over the content to a fresh PR - perhaps that fixes this issue - I haven't seen this issue before

**Pull request closed without merging**
