### PR TITLE
Getting started with Data Visualization using Pandas

### LINKED ISSUE #530: Getting started with Data Visualization using Pandas
### Brief Summary: 
**Data Visualization** is the process of placing data into patterns in order to understand it better, **Pandas** library is powerful because it is built on **Matplotlib** and it allows us to do data manipulation and analysis.
Basically, this tutorial will be for beginners who are interested in **data science** and I will use **Pandas** with **Python**.

### Key Takeaways: 
- An overview of **data science** and **Pandas** library.
- How to handle the datasets and importing them.
- The different types of **plots** and **charts** and how to implement them (line chart/Scatter Plot/Bar Chart/...).

Note: the article about pandas [here](https://www.section.io/engineering-education/data-analytics-using-pandas/) talks about the basics of **Analysis**, mine will be about **Visualization** after analyzing data, and the points I'm going to write about does not exist in that article.

Note: I'm thinking of writing part 2 of this tutorial which will be about **Plotly** but I'm not sure yet.
### References: 
N/A

### PR DESCRIPTION
**Pull request by ahmadmardeni1**
Note: I designed the hero image.
#### Preliminary Checks - Formatting and Structure 
- [x] Does your article follow any of the suggested structure formats? - **see [example formats](https://github.com/section-io/engineering-education/blob/master/CONTRIBUTING.md#example-format-structure)**
- [x] Is your article properly formatted in Markdown? - **see [Github Markdown guide](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet)**
- [x] Have you used the correct folder and file structure? - **see [Contribution Guidelines](https://github.com/section-io/engineering-education/blob/master/CONTRIBUTING.md)**
- [x] Is your article over 750 words? - **Tool**: [Wordcounter.net](https://wordcounter.net)
- [x] Have you used our preferred heading structure? - **[H3 (###) and up](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet#headers)**
- [x] Does your article provide enough value and detail about your topic? - **Articles should be clear, accurate, and fully explained.**
- [x] Can your article be understood by beginners? - **Assume the audience is smart but has no prior exposure to the common terminology in your article.**
- [x] Have you included a hero image that is 600x400 pixels and have the copyright to use it? - **Tools:** [Pixlr Image Editor](https://pixlr.com/e) for resizing and [Unsplash](https://unsplash.com) for Creative Commons images
- [x] In your PR - add a comment that states **["This fixes #(enter your Idea Content Form #)"](https://youtu.be/TKJ4RdhyB5Y?t=278)** to link and close your Idea Content (issue) when the PR is merged.
      

#### Grammar Checks
- [x] Have you spellchecked and grammar checked your article? - **Tool:** [Grammarly](https://grammarly.com)
- [x] Have you checked your article for readability? - **Tool:** [Hemmingway](http://www.hemingwayapp.com)
- [x] Have you added sources for quotes and images that aren't yours?

#### Technical Checks
- [x] Are your code snippets properly formatted for syntax highlighting - **see [Syntax guide](https://gohugo.io/content-management/syntax-highlighting)**

### Contribution Guidelines
For first-time contributors and for more details, **see [Contributing Guidelines](https://github.com/section-io/engineering-education/blob/master/CONTRIBUTING.md)**

This fixes #530

### CODE REVIEW

**Comment by ahmadmardeni1** [comment]
This fixes #530

**Comment by hectorkambow** [comment]
plagiarism check done

**Review by lalith1403 — CHANGES_REQUESTED** [review]
@ahmadmardeni1 Great article. A few suggestions are given to enhance readability. 
General feedback:
1. Break down huge paragraphs into smaller pieces of information you want to convey. 
2. Check the links before you include them in the article. We want the reader to find all the important information in the article itself. In a worst-case scenario, we guide them to a link that adds further value. 
3. Check if all the article's images are your own or any credits need to be given. If yes, mention the source. Else, ignore the final point.

Excited to read the updated article.

**Comment by ahmadmardeni1** [comment]
Hello @lalith1403 
Thank you for your time and your suggestions 
I did the changes but about the zip file, it is available on this link, you just have to press download 
All images in the article are mine also I designed the hero image.
All links are working fine.

**Comment by lalith1403** [comment]
> Hello @lalith1403
> Thank you for your time and your suggestions
> I did the changes but about the zip file, it is available on the link, you just have to press download
> All images in the article are mine also I designed the hero image.
> And all links are working fine.

Sorry about the link. I got a 404 error yesterday, so asked you to cross-check. A few minor changes and this should be ready for the final review. 

1. You mention, you can do data analysis. It’s actually you can perform data analysis.change this wherever necessary.
2. The histogram is providing -> the histogram provides
3. Line 23. After importing and performing data analysis on the dataset. Ensure consistency in verb forms.
4. Line 94. If we want to make it horizontal we just have to change our code to -> To obtain a horizontal bar chart, we modify our code as follows:
5. Line 116: to let you get the idea better -> to develop the idea better.

The sentences are compounded using commas. It begins difficult to read long sentences. Go through the entire article and break down the sentences into smaller sentences. I do not mean break it down into smaller paragraphs. Also, a Grammarly check after the changes will ensure minimal grammatical errors. I observed a few grammatical errors, and hence the suggestion.

**Comment by ahmadmardeni1** [comment]
Good afternoon @lalith1403 
I did the edits but I didn't find  "you can do data analysis" sentence in my tutorial, can you highlight it for me, please?
I tried to break down the sentences into smaller ones as much as possible, but feel free to ask me to change anything.
I will be happy to improve my writing skills through your tips and suggestions.

**Review by lalith1403 — APPROVED** [review]
Line 147-> you can do -> you can use the process mentioned above

Just a small change and this should be ready for final review. I have approved the changes. Ensure line 147 is changed.

**Comment by lalith1403** [comment]
> Good afternoon @lalith1403 
> 
> I did the edits but I didn't find  "you can do data analysis" sentence in my tutorial, can you highlight it for me, please?
> 
> I tried to break down the sentences into smaller ones as much as possible, but feel free to ask me to change anything.
> 
> I will be happy to improve my writing skills through your tips and suggestions.

Avoid using do in the sentences. The article was well structured. The reviews mention a few patterns that need to modified throughout the article. 	The article is well written 👍. All the best.

**Pull request merged**
