### PR TITLE
Machine Learning Model Deployments with Django

### PR DESCRIPTION
**Pull request by Priyankk18k**
Here you will learn how to deploy your Machine learning model into production environment with the help of Django Framework. The Focus of the article is Towards making an API of your machine learning model so that everyone can access your model.

### CODE REVIEW

**Comment by hectorkambow** [comment]
Good afternoon Kurt 👋 @kurt-sectionio 🚀 - wanted to ask if you could give this article a tech review before we publish whenever you have a moment.
Thank you

**Comment by Priyankk18k** [comment]
Hi @kurt-sectionio @hectorkambow ,
The Major Focus of the Article is to show how to deploy ML models using rest API. I'm Using Django Rest Framework  for that and for this article there is a prerequisite that we should know Django. 
I can add more paragraph so that one can understand urls.py, view.py, serializers.py etc but i think a Proper article for that will be benefitial else the length of this article will increase. Can you tell me what are your thoughts on this?

**Comment by kurt-sectionio** [comment]
I understand that the length will increase and that's fine as long as the content is good. I also think if you leave out a lot of the model-building stuff that you will end up with something with manageable length. So yes, I think a brief introduction to Django would be good and then focus on the Django elements for serving an ML model. Consider that there are many more Flask tutorials available for this kind of application. Your readers don't need to really *understand* Django, but I think you can give them a basic understanding of Django in the beginning and then dig into the specifics of this application. I also just thought: you could link to a github repo with your model-building code and include your discussion about h5 model format as a comment in the code. Does that sound manageable?

**Comment by Priyankk18k** [comment]
Ok I will add some more lines so that one can understand what is django and then i will foucs on the elements of this particular application.

**Comment by hectorkambow** [comment]
> Ok I will add some more lines so that one can understand what is django and then i will foucs on the elements of this particular application.

**Comment by hectorkambow** [comment]
> Ok I will add some more lines so that one can understand what is django and then i will foucs on the elements of this particular application.

Length of the article should never be an issue - just as Kurt mentioned as long as the content is good 👍

**Comment by hectorkambow** [comment]
closing due to inactivity - can be re-opened at any time @Priyankk18k 🚀 
👍

**Pull request closed without merging**
