### PR TITLE
CRUD operation with MySQL using Vue.js and PHP 

### PR DESCRIPTION
**Pull request by CodeLeom**
#### Preliminary Checks - Formatting and Structure 
- [x] Does your article follow any of the suggested structure formats? - **see [example formats](https://github.com/section-io/engineering-education/blob/master/CONTRIBUTING.md#example-format-structure)**
- [x] Is your article properly formatted in Markdown? - **see [Github Markdown guide](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet)**
- [x] Have you used the correct folder and file structure? - **see [Contribution Guidelines](https://github.com/section-io/engineering-education/blob/master/CONTRIBUTING.md)**
- [x] Is your article over 750 words? - **Tool**: [Wordcounter.net](https://wordcounter.net)
- [x] Have you used our preferred heading structure? - **[H3 (###) and up](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet#headers)**
- [x] Does your article provide enough value and detail about your topic? - **Articles should be clear, accurate, and fully explained.**
- [x] Can your article be understood by beginners? - **Assume the audience is smart but has no prior exposure to the common terminology in your article.**
- [x] Have you included a hero image that is 600x400 pixels and have the copyright to use it? - **Tools:** [Pixlr Image Editor](https://pixlr.com/e) for resizing and [Unsplash](https://unsplash.com) for Creative Commons images
- [ ] In your PR - add a comment that states **["This fixes #(enter your Idea Content Form #)"](https://youtu.be/TKJ4RdhyB5Y?t=278)** to link and close your Idea Content (issue) when the PR is merged.

**NOTE: (1st time contributors - submit ONLY one article to get familiar with the process and style-once published, you can then submit any number of articles.)**
      
#### Grammar Checks
- [x] Have you spellchecked and grammar checked your article? - **Tools:** [Write&Improve](https://writeandimprove.com/?lang=en-GB) - [ProWritingAid](https://prowritingaid.com/) -  [Grammarly](https://grammarly.com) 
- [x] Have you checked your article for readability? - **Tool:** [Hemmingway](http://www.hemingwayapp.com)
- [x] Have you added sources for quotes and images that aren't yours?

#### Technical Checks
- [x] Are your code snippets properly formatted for syntax highlighting - **see [Syntax guide](https://gohugo.io/content-management/syntax-highlighting)**

### Contribution Guidelines
For first-time contributors and for more details, **see [Contributing Guidelines](https://github.com/section-io/engineering-education/blob/master/CONTRIBUTING.md)**

### CODE REVIEW

**Comment by hectorkambow** [comment]
👋 Thank you for submitting this PR - we will review it ASAP - all PRs go into our queue will be looked over before being approved to be published.

**Comment by CodeLeom** [comment]
@hectorkambow I hope my PR has not been forgotten

**Comment by hectorkambow** [comment]
> @hectorkambow I hope my PR has not been forgotten

No Sir by no means - just working through a higher volume of PRs. I'll jump on yours right away 🚀

**Comment by hectorkambow** [comment]
👋  Good morning/evening @CodeLeom  

Although your article topic seems like a great informative topic - we want to make sure we are striving to create new, original, and unique content - that can not be easily found elsewhere. 

Upon running your article through our 3rd party plagiarism checker, it raised a few red flags - and the % was higher than we typically like to see. 
[CRUD operation with MySQL using Vue.js and PHP #1021.pdf](https://github.com/section-io/engineering-education/files/5803905/CRUD.operation.with.MySQL.using.Vue.js.and.PHP.1021.pdf)

I did notice your sources and citations in the article - which is great and encouraged always. 👍  Yet, the article should have its own unique substance and not use definitions as filler content.

Some of the sentences seem to require some revision as well - I would always recommend that you go over our [resources page](https://github.com/section-io/engineering-education/blob/master/new_contributors/resources-page.md) for various helpful links like proofreading services, style structure, and grammar tools.

**Comment by hectorkambow** [comment]
Will be closing this PR - to make some room in the queue. While you work on your article - please ping me when you'd like to re-open it again. 👍

**Pull request closed without merging**
