### PR TITLE
Top 10 in demand technologies to learn

### PR DESCRIPTION
**Pull request by JudyNduati**
I have added an index.md file and the header image hero.jpg

Description
Technology is growing at a tremendous rate, as an IT professional it is almost like a survival tactic to keep yourself updated with the evolving technology and market trends. This article describes 10  demanding technologies to learn and earn skills

### CODE REVIEW

**Comment by hectorkambow** [comment]
Plagiarism check is done

**Comment by hectorkambow** [comment]
👋 Hi @AskAlice - Happy Friday! 
Wanted to ask if you could give this "10 in-demand technologies to learn" article a tech review before we publish whenever you have a moment. 
I looked it over and it looked quite nice - I just wanted to make sure everything (presented) was accurate - and/or if there was anything else we could add. 

Thank you 🚀

**Comment by hectorkambow** [comment]
@ninjaginja 👋  Good afternoon Molly - wanted to ask if you could give this article a tech review - 
Should be ready to publish - pending any technical edits  
Thank you 
🚀

**Comment by ninjaginja** [comment]
@JudyNduati . I did a preliminary review of your article, and while the concept of identifying top technologies in demand has a lot of value, the readability (grammar, word choice, and overall flow) of this article needs quite a bit of attention. I'd suggest trying to tap into your peer networks to see if you can get some editing guidance on how to elevate the readability of this article. Feel free to make revisions and resubmit when ready. We'll keep this PR open in the meantime.

**Comment by JudyNduati** [comment]
@ninjaginja I have worked on the revisions. Your suggestions helped me improve the article readability

**Comment by ninjaginja** [comment]
@JudyNduati I went ahead and made some edits to the beginning of the article so you have a better idea of the types of readability edits that we're seeking. Please take a look at the edits made in the most recent commit and try to apply them to the remainder of the article. Thanks.

**Comment by JudyNduati** [comment]
@ninjaginja I have worked on the revisions you suggested and believe  the article readability is improved

**Comment by ninjaginja** [comment]
@JudyNduati I made some more edits. There were some inaccuracies in your Edge Computing paragraph that I corrected as well. I think the article needs a conclusion at the end to tie it all together. As it stands now, it just lingers on the last item in the list.

**Comment by JudyNduati** [comment]
@ninjaginja I have added a conclusion. Thanks, Molly for the insights

**Comment by JudyNduati** [comment]
@ninjaginja I added a conclusion

**Comment by ninjaginja** [comment]
Thanks @JudyNduati. I hope the back-and-forth on this article helps guide your future contributions :) As a side note, we're planning to roll out a new payout structure in the near future that rewards contributors who submit articles that require little/no editing intervention. Leading up to those changes, we're seeking to guide students as much as possible on what we look for in submitted content.

**Pull request merged**
