### PR TITLE
Introduction to Kafka

### PR DESCRIPTION
**Pull request by adithbharadwaj**
Requesting the team to review my article on Kafka. The article introduces the readers to the basics of Kafka, its history, architecture, and installation. There are three images: hero.jpg, kafka-architecture.png, publish-subscribe.png

### CODE REVIEW

**Comment by hectorkambow** [comment]
Good afternoon 👋 @mwickman  - wanted to ask if you could give this article a tech review before we publish.
Thank you 🚀

**Comment by hectorkambow** [comment]
Thank you @mwickman - absolutely - 
@adithbharadwaj  - if you could please incorporate an example "of how a client consumer/producer might interact with Kafka. Like maybe how to interact with Kafka using Nodejs specifically."

**Comment by adithbharadwaj** [comment]
> Thank you @mwickman - absolutely -
> @adithbharadwaj - if you could please incorporate an example "of how a client consumer/producer might interact with Kafka. Like maybe how to interact with Kafka using Nodejs specifically."

@hectorkambow Sure I will include an example on how to use Kafka with Nodejs and push the changes shortly.

**Comment by hectorkambow** [comment]
> > Thank you @mwickman - absolutely -
> > @adithbharadwaj - if you could please incorporate an example "of how a client consumer/producer might interact with Kafka. Like maybe how to interact with Kafka using Nodejs specifically."
> 
> @hectorkambow Sure I will include an example on how to use Kafka. Is it ok if I include an example of how to use Kafka in Python as I don't have much experience and knowledge in using Nodejs with Kafka? I have experience with using Kafka in Python and I believe it will be easier for new readers to understand Kafka better in a language like Python. Is that ok?

@adithbharadwaj  - not a problem - please proceed with the example. 👍

**Comment by adithbharadwaj** [comment]
> > > Thank you @mwickman - absolutely -
> > > @adithbharadwaj - if you could please incorporate an example "of how a client consumer/producer might interact with Kafka. Like maybe how to interact with Kafka using Nodejs specifically."
> > 
> > 
> > @hectorkambow Sure I will include an example on how to use Kafka. Is it ok if I include an example of how to use Kafka in Python as I don't have much experience and knowledge in using Nodejs with Kafka? I have experience with using Kafka in Python and I believe it will be easier for new readers to understand Kafka better in a language like Python. Is that ok?
> 
> @adithbharadwaj - not a problem - please proceed with the example. +1

@hectorkambow I have added an example on how to use and run Kafka in Python. Please review the article and tell me if i need to make any changes.

**Pull request merged**
