### PR TITLE
Article - Web Application Architectures 101

### PR DESCRIPTION
**Pull request by cyberShaw**
Added an article that helps students and developers understand various methods and architectures of developing web apps, like Server Side Rendering, Client Side Rendering and includes a detailed comparison between them. 

Please review and merge! 😄

### CODE REVIEW

**Comment by hectorkambow** [comment]
Good afternoon 👋 @gwritz  🚀 - wanted to ask if you could give this article a tech review before we publish.
Thank you

**Comment by ninjaginja** [comment]
@cyberShaw Did you create the /csr-ssr.webp image, or did you source that from a third-party? If sourced, please provide a link to the referenced image.

**Comment by cyberShaw** [comment]
Ah dang. I forgot to provide the attribution to the third party. I'll send in a commit first thing tomorrow morning!

**Comment by ninjaginja** [comment]
No worries, thank you!

**Comment by cyberShaw** [comment]
> No worries, thank you!

I've added the image source, as requested 😄 
I'll be sure to not miss this from next time!

**Pull request merged**
