### PR TITLE
MEAN vs MERN

### PR DESCRIPTION
**Pull request by Richu98**
I have discussed about  Mean and MERN stack with respect to different parameters

### CODE REVIEW

**Comment by hectorkambow** [comment]
@Richu98 - good afternoon Richu - started a preliminary review on your article 
Looks like some great content - 
If you could review the article again - upon a first review I stumbled across some grammar issues and some sentences that were a bit rough. 
Thank you 🚀

**Comment by Richu98** [comment]
Hi @hectorkambow 
I have updated the article. Please Review

**Comment by hectorkambow** [comment]
Review the edits made here https://github.com/section-io/engineering-education/pull/225/commits/f54888808ec0d631c8b8a0de668b2346843f42a0

By fetching/pulling. 

The article required quite a few changes and is still a bit difficult to read. @Richu98 

Please review these changes and moving forward keep these edits in mind

**Comment by Richu98** [comment]
Okay @hectorkambow but the hemmingway score was 9. I will try to simplify the articles.
I will keep it in mind in the future articles. Do I need to do any more changes ?

**Comment by hectorkambow** [comment]
> Okay @hectorkambow but the hemmingway score was 9. I will try to simplify the articles.
> I will keep it in mind in the future articles. Do I need to do any more changes ?

Totally understand - the Hemmingway sometimes is a bit tricky - use it more as a guide. 🚀

**Comment by hectorkambow** [comment]
👋  Hi @lcaballero - wanted to ask if you could give this MEAN vs MERN article a tech review before we publish - whenever you have a moment. 
Thank you 🚀

**Pull request merged**
