### PR TITLE
Understand basics of Django Rest Framework

### PR DESCRIPTION
**Pull request by Priyankk18k**
Applied the change to understand basics of Django Rest Framework.

### CODE REVIEW

**Comment by hectorkambow** [comment]
Just finished up a preliminary review on your article - upon passing it through our 3rd party plagiarism check - it raised a few red flags. 
Please see attached - and revisit the article - we can not have sentences that are copied from any other sources (without citations) and your article should be original content. 

[machine-learning-article-py.pdf](https://github.com/section-io/engineering-education/files/5241252/machine-learning-article-py.pdf)


Please see attached.

**Comment by Priyankk18k** [comment]
Ok sure. I will Look into it to make it more real. Actually i have also Attached the links for the Docs After writing it. But Anyways I will change it.

**Comment by hectorkambow** [comment]
> Ok sure. I will Look into it to make it more real. Actually i have also Attached the links for the Docs After writing it. But Anyways I will change it.

Thank you - that's great - adding the links at the end is great - but we should stem away from using direct language from any other sources - for example unless we are making a point about that sentence.

**Comment by hectorkambow** [comment]
simply closing PR to make room in the Queue - can be REOPENED at any time 👍

**Pull request closed without merging**
