### PR TITLE
Understanding the LAMP Stack

### LINKED ISSUE #736: Understanding the LAMP Stack
### Brief Summary: 
Solution Stacks are combination of software or application programs used to form a computing platform. This article will discuss about one such stack - the LAMP Stack. The article will include a brief description about its components, usage and applications.

### Key Takeaways: 
The readers will be able to understand the 4 main parts of LAMP Stack and how they can be used to create web applications. The readers will also learn about the importance of each part:
1)**L**inux - OS
2)**A**pache - Web layer
3)**M**ySQL - Database layer
4)**P**HP and its alternatives - Scripting layer 

### References: 
https://en.wikipedia.org/wiki/LAMP_(software_bundle)

### PR DESCRIPTION
**Pull request by kvardhan10**
#### Preliminary Checks - Formatting and Structure 
- [x] Does your article follow any of the suggested structure formats? - **see [example formats](https://github.com/section-io/engineering-education/blob/master/CONTRIBUTING.md#example-format-structure)**
- [x] Is your article properly formatted in Markdown? - **see [Github Markdown guide](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet)**
- [x] Have you used the correct folder and file structure? - **see [Contribution Guidelines](https://github.com/section-io/engineering-education/blob/master/CONTRIBUTING.md)**
- [x] Is your article over 750 words? - **Tool**: [Wordcounter.net](https://wordcounter.net)
- [x] Have you used our preferred heading structure? - **[H3 (###) and up](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet#headers)**
- [x] Does your article provide enough value and detail about your topic? - **Articles should be clear, accurate, and fully explained.**
- [x] Can your article be understood by beginners? - **Assume the audience is smart but has no prior exposure to the common terminology in your article.**
- [x] Have you included a hero image that is 600x400 pixels and have the copyright to use it? - **Tools:** [Pixlr Image Editor](https://pixlr.com/e) for resizing and [Unsplash](https://unsplash.com) for Creative Commons images
- [x] In your PR - add a comment that states **["This fixes #(enter your Idea Content Form #)"](https://youtu.be/TKJ4RdhyB5Y?t=278)** to link and close your Idea Content (issue) when the PR is merged.

**NOTE: (1st time contributors - submit ONLY one article to get familiar with the process and style-once published, you can then submit any number of articles.)**
      
#### Grammar Checks
- [x] Have you spellchecked and grammar checked your article? - **Tools:** [Write&Improve](https://writeandimprove.com/?lang=en-GB) - [ProWritingAid](https://prowritingaid.com/) -  [Grammarly](https://grammarly.com) 
- [x] Have you checked your article for readability? - **Tool:** [Hemmingway](http://www.hemingwayapp.com)
- [x] Have you added sources for quotes and images that aren't yours?

#### Technical Checks
- [x] Are your code snippets properly formatted for syntax highlighting - **see [Syntax guide](https://gohugo.io/content-management/syntax-highlighting)**

### Contribution Guidelines
For first-time contributors and for more details, **see [Contributing Guidelines](https://github.com/section-io/engineering-education/blob/master/CONTRIBUTING.md)**

This fixes #736

### CODE REVIEW

**Comment by kvardhan10** [comment]
*article

**Comment by hectorkambow** [comment]
👋 Thank you for submitting this PR - we will review it ASAP - all PRs go into our queue will be looked over before being approved to be published.

**Comment by kvardhan10** [comment]
Looking forward to it.

**Review by lalith1403 — CHANGES_REQUESTED** [review]
The information mentioned is apt. The structure is good. However, I feel additional content is required. One who is well versed with CS would know about how a full-stack system works. Some more details and explanation is required. Also, add a section on applications.

**Comment by kvardhan10** [comment]
okay. I'll make another section and explain how the LAMP stack works. While I'm on that, I'll also draw a flowchart for the same. I'll update the index.md file and add an image by tomorrow.

**Comment by hectorkambow** [comment]
plagiarism check done

**Comment by kvardhan10** [comment]
> The information mentioned is apt. The structure is good. However, I feel additional content is required. One who is well versed with CS would know about how a full-stack system works. Some more details and explanation is required. Also, add a section on applications.

Done! Added two more sections - one which tells how the LAMP Stack works and another about its usage. Also, drew a flowchart for better understanding and committed the same.

**Pull request merged**
