### PR TITLE
EngEd Content Idea Suggestion template

### PR DESCRIPTION
**Pull request by hectorkambow**
Testing Issue (templates) for EngEd idea form

### CODE REVIEW

**Comment by hectorkambow** [comment]
@ninjaginja 
This is the Template I've created so far - I added the front matter (with added detail for students to read)

My understanding is this would be used instead of the google content form - filling one of these out will easily transfer over to a PR when they are ready? 

I'll test it out some more - just wanted to get your thoughts on this 🚀

**Comment by ninjaginja** [comment]
@hectorkambow I think the front matter may be confusing to people. Plus, they likely won't have a good feel for a title and summary description until they actually write the article. This is simply intended to replace the Google Form where they submit their content suggestions.

I'm note sure what you mean by 'filling one of these out will easily transfer over to a PR when they are ready?'

**Comment by ninjaginja** [comment]
@hectorkambow I'd also suggest creating a personal repo and testing the issue template functionality there.

**Comment by hectorkambow** [comment]
Closing to make room - trying on personal repo

**Pull request closed without merging**
