### PR TITLE
How to build a GraphQL Server Using Node.js

### PR DESCRIPTION
**Pull request by DesignrKnight**
#### Preliminary Checks - Formatting and Structure 
- [x] Does your article follow any of the suggested structure formats? - **see [example formats](https://github.com/section-io/engineering-education/blob/master/CONTRIBUTING.md#example-format-structure)**
- [x] Is your article properly formatted in Markdown? - **see [Github Markdown guide](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet)**
- [x] Have you used the correct folder and file structure? - **see [Contribution Guidelines](https://github.com/section-io/engineering-education/blob/master/CONTRIBUTING.md)**
- [x] Is your article over 750 words? - **Tool**: [Wordcounter.net](https://wordcounter.net)
- [x] Have you used our preferred heading structure? - **[H3 (###) and up](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet#headers)**
- [x] Does your article provide enough value and detail about your topic? - **Articles should be clear, accurate, and fully explained.**
- [x] Can your article be understood by beginners? - **Assume the audience is smart but has no prior exposure to the common terminology in your article.**
- [x] Have you included a hero image that is 600x400 pixels and have the copyright to use it? - **Tools:** [Pixlr Image Editor](https://pixlr.com/e) for resizing and [Unsplash](https://unsplash.com) for Creative Commons images
- [x] In your PR - add a comment that states **["This fixes #(enter your Idea Content Form #)"](https://youtu.be/TKJ4RdhyB5Y?t=278)** to link and close your Idea Content (issue) when the PR is merged.
      

#### Grammar Checks
- [x] Have you spellchecked and grammar checked your article? - **Tool:** [Grammarly](https://grammarly.com)
- [x] Have you checked your article for readability? - **Tool:** [Hemmingway](http://www.hemingwayapp.com)
- [x] Have you added sources for quotes and images that aren't yours?

#### Technical Checks
- [x] Are your code snippets properly formatted for syntax highlighting - **see [Syntax guide](https://gohugo.io/content-management/syntax-highlighting)**

### Contribution Guidelines
For first-time contributors and for more details, **see [Contributing Guidelines](https://github.com/section-io/engineering-education/blob/master/CONTRIBUTING.md)**

### Linked Issue
#469 : How to build a GraphQL Server Using Node.js

### CODE REVIEW

**Comment by DesignrKnight** [comment]
Converted PR to draft as I realised some commits from my clone is not pushed due to some reasons to upstream. Will update ASAP and confirm when ready. 
Thank you

**Comment by DesignrKnight** [comment]
@hectorkambow 
I have updated the PR to be ready for review. The article around 3000 words, I have tried to make it easy to follow as much possible. Kindly review

Thank you

**Comment by hectorkambow** [comment]
👋  Thank you for submitting this PR - we will review it ASAP - all PRs go into our queue will be looked over before being approved to be published.

**Comment by DesignrKnight** [comment]
Thanks for the update. Looking forward to feedbacks

**Comment by hectorkambow** [comment]
plagiarism check done

**Comment by ninjaginja** [comment]
Really fantastic article @DesignrKnight !!! Thanks for the thorough tutorial and attention to detail :)... I did make some formatting updates that you may take note of for subsequent content development.

**Comment by DesignrKnight** [comment]
Thank you so much @ninjaginja and @hectorkambow 
Glad to contribute. I will learn from the edits you made and try to be more mindful of the formatting.

Looking forward to another article writing soon

**Pull request merged**
