### PR TITLE
Node authentication api

### PR DESCRIPTION
**Pull request by LinusMuema**

### CODE REVIEW

**Comment by LinusMuema** [comment]
The article is about a basic authentication server with Nodejs that gives API endpoints for authentication and provides a JSON web token with the login and signup requests.

**Comment by LinusMuema** [comment]
The images included are 
`hero.png` for the blog header
Then the other images follow each other as below :
`nodemon.png`
`app-router.png`
`route-signup.png`
`postman-signup-1.png`
`jwt-generate.png`
`json-token.png`
`login.png`
`jwt-test.png`

**Comment by hectorkambow** [comment]
@LinusMuema - just started with a preliminary review on your article - just wanted to ping you - and make sure you add your author image and bio to be included at the end of your articles.- in the author repo.
After that, your article will be ready to move on to tech review - and then published - pending any further edits 👍

**Comment by LinusMuema** [comment]
@hectorkambow 
* Added author details

**Pull request merged**
