### PR TITLE
Getting started with Yii 2 PHP Framework

### LINKED ISSUE #697: Getting started with yii2 php framework
### Brief Summary: 
Yii2 PHP framework is one of the best web frameworks for building simple and scalable web applications. We will look at building a simple web app using yii2 framework.
### Key Takeaways: 
The reader will be in a position to:
- install and setup yii2 framework.
- create a new yii2 project
- connect a database to the project
- create database models using gii 
- register and manage users
- set up routing using PHP URL manager.
### References: 
N/A

### PR DESCRIPTION
**Pull request by Erastuskanyatta**
#### Preliminary Checks - Formatting and Structure 
- [x] Does your article follow any of the suggested structure formats? - **see [example formats](https://github.com/section-io/engineering-education/blob/master/CONTRIBUTING.md#example-format-structure)**
- [x] Is your article properly formatted in Markdown? - **see [Github Markdown guide](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet)**
- [x] Have you used the correct folder and file structure? - **see [Contribution Guidelines](https://github.com/section-io/engineering-education/blob/master/CONTRIBUTING.md)**
- [x] Is your article over 750 words? - **Tool**: [Wordcounter.net](https://wordcounter.net)
- [x] Have you used our preferred heading structure? - **[H3 (###) and up](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet#headers)**
- [x] Does your article provide enough value and detail about your topic? - **Articles should be clear, accurate, and fully explained.**
- [x] Can your article be understood by beginners? - **Assume the audience is smart but has no prior exposure to the common terminology in your article.**
- [x] Have you included a hero image that is 600x400 pixels and have the copyright to use it? - **Tools:** [Pixlr Image Editor](https://pixlr.com/e) for resizing and [Unsplash](https://unsplash.com) for Creative Commons images
- [x] In your PR - add a comment that states **["This fixes #(enter your Idea Content Form #)"](https://youtu.be/TKJ4RdhyB5Y?t=278)** to link and close your Idea Content (issue) when the PR is merged.

**NOTE: (1st time contributors - submit ONLY one article to get familiar with the process and style-once published, you can then submit any number of articles.)**
      
#### Grammar Checks
- [x] Have you spellchecked and grammar checked your article? - **Tools:** [Write&Improve](https://writeandimprove.com/?lang=en-GB) - [ProWritingAid](https://prowritingaid.com/) -  [Grammarly](https://grammarly.com) 
- [x] Have you checked your article for readability? - **Tool:** [Hemmingway](http://www.hemingwayapp.com)
- [ ] Have you added sources for quotes and images that aren't yours?

#### Technical Checks
- [x] Are your code snippets properly formatted for syntax highlighting - **see [Syntax guide](https://gohugo.io/content-management/syntax-highlighting)**

### Contribution Guidelines
For first-time contributors and for more details, **see [Contributing Guidelines](https://github.com/section-io/engineering-education/blob/master/CONTRIBUTING.md)**

this fixes #697

### CODE REVIEW

**Comment by hectorkambow** [comment]
👋 Thank you for submitting this PR - we will review it ASAP - all PRs go into our queue will be looked over before being approved to be published.

**Comment by Erastuskanyatta** [comment]
My article has not  been reviewed yet since I submitted the PR. It's almost
20 days now. Please help.Thanks

**Comment by hectorkambow** [comment]
plagiarism check done

**Comment by WanjaMIKE** [comment]
@Erastuskanyatta 
I am reviewing the article.  I had trouble finding this article in the article-master folder.
I later realized that you had named your folder as php-yii2-framework rather than getting-started-with-yii-2-php-framework.

In future PRs, please use the article title as the folder name to avoid confusion.

**Comment by Erastuskanyatta** [comment]
@WanjaMIKE I will avoid that mistake in the next PRs,Am sorry for that mistake.

**Comment by WanjaMIKE** [comment]
@Erastuskanyatta 
Just finished the preliminary article. I must say -- this is quite good especially for first article. Nice job. I have a few pointers.
1. I realized that you have two similar images. 1.png and web.png. Should 1 be deleted or they serve different purpose?
2.  The images are referenced with full links - like this web display
rather than web display    -- according documentation.
3. Is the folder created lampp or xampp? I realized you provided a link to download xampp.
4. Try to be consisted with ### headings when describing steps.

Could you clarify on the lampp/xampp part before we go to tech review.

**Comment by Erastuskanyatta** [comment]
@WanjaMIKE                                                                                                                                                             1. The images should remain.One images is for the main page while the the other is for the portifolio page.
2. lampp/xampp part clarified. The folder should be `opt/lampp` .                                                                             Please proceed. Thank you

**Review by WanjaMIKE — APPROVED** [review]
A nice article. It's quite easy to follow and understand. The provided code snippets work as expected. Keep up!

**Comment by Erastuskanyatta** [comment]
Thank you @WanjaMIKE  .

**Comment by Erastuskanyatta** [comment]
@WanjaMIKE  maybe you can also be the  Reviewer to my second article.

**Comment by WanjaMIKE** [comment]
I will check out if it's in my area of expertise. Thanks

**Comment by Erastuskanyatta** [comment]
@WanjaMIKE  I hope so, though its about Mariadatabase and am using PHP. Thanks

**Comment by WanjaMIKE** [comment]
MariaDB is basic database. I will check it out

**Comment by Erastuskanyatta** [comment]
@WanjaMIKE  Thank you.

**Pull request merged**
