### PR TITLE
JavaScript Particles Effect with TsParticles

### LINKED ISSUE #421: Particle Effect With Particle.js
### Brief Summary: 
In this tutorial, I’m going to talk about particles.js, a javascript library that let you create a dynamic particle effect on your webpage.

### Key Takeaways: 
1. Installation and Usage
2. Setup
3. Coding
4. Moving some particles
5. Output
### References: 

'N/A'.)

### PR DESCRIPTION
**Pull request by kimkimani**
#### Preliminary Checks - Formatting and Structure 
- [x] Does your article follow any of the suggested structure formats? - **see [example formats](https://github.com/section-io/engineering-education/blob/master/CONTRIBUTING.md#example-format-structure)**
- [x] Is your article properly formatted in Markdown? - **see [Github Markdown guide](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet)**
- [x] Have you used the correct folder and file structure? - **see [Contribution Guidelines](https://github.com/section-io/engineering-education/blob/master/CONTRIBUTING.md)**
- [x] Is your article over 750 words? - **Tool**: [Wordcounter.net](https://wordcounter.net)
- [x] Have you used our preferred heading structure? - **[H3 (###) and up](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet#headers)**
- [x] Does your article provide enough value and detail about your topic? - **Articles should be clear, accurate, and fully explained.**
- [x] Can your article be understood by beginners? - **Assume the audience is smart but has no prior exposure to the common terminology in your article.**
- [x] Have you included a hero image that is 600x400 pixels and have the copyright to use it? - **Tools:** [Pixlr Image Editor](https://pixlr.com/e) for resizing and [Unsplash](https://unsplash.com) for Creative Commons images
- [x] In your PR - add a comment that states **["This fixes #(enter your Idea Content Form #)"](https://youtu.be/TKJ4RdhyB5Y?t=278)** to link and close your Idea Content (issue) when the PR is merged.
      

#### Grammar Checks
- [x] Have you spellchecked and grammar checked your article? - **Tool:** [Grammarly](https://grammarly.com)
- [x] Have you checked your article for readability? - **Tool:** [Hemmingway](http://www.hemingwayapp.com)
- [x] Have you added sources for quotes and images that aren't yours?

#### Technical Checks
- [x] Are your code snippets properly formatted for syntax highlighting - **see [Syntax guide](https://gohugo.io/content-management/syntax-highlighting)**

### Contribution Guidelines
For first-time contributors and for more details, **see [Contributing Guidelines](https://github.com/section-io/engineering-education/blob/master/CONTRIBUTING.md)**
fixes #421

### CODE REVIEW

**Comment by kimkimani** [comment]
@hectorkambow, Pinging you for a small check. I got several code blocks on this guide, I believe they form like half of the content. Running plagiarism check, I got a high number of red flags. Would you mind giving it a plagiarism check on your end? I just want to know if the plagiarism flags are okay before the actual reviews start.

**Comment by hectorkambow** [comment]
Plagiarism check done

**Comment by hectorkambow** [comment]
👋 Hi @AskAlice 
This is the "JavaScript Particles Effect with TsParticles" article I spoke to you about. 
It seems like a cool article and the animations are cool. 
Wanted to ask if you could please give this article a tech review whenever you get a moment. 
Thank you again 🚀

**Review by AskAlice — APPROVED** [review]
well done, I've used this library in my own projects and I like what you've done with it.

You could potentially add ```topics: [Node.js]``` on line 10 of your index.md

**Pull request merged**
