### PR TITLE
5-reasons-why-chatbots-are-the-new-black - vrinda jain

### PR DESCRIPTION
**Pull request by vrindajain**

### CODE REVIEW

**Comment by hectorkambow** [comment]
Good morning @vrindajain - starting a preliminary review on your article - in the meantime, if you include a short Author Biography and Headshot image to be included at the end of your articles. There is a separate folder for author in the repo as well. 👍

**Comment by hectorkambow** [comment]
Good afternoon @niccolox  - wanted to ask if you could give this article topic a tech review whenever you have a moment. 
Thank you 🚀

**Comment by niccolox** [comment]
looking now

**Comment by vrindajain** [comment]
Hi @niccolox 

Thanks for changing these, I agree with your suggestions completely. 😃

**Comment by niccolox** [comment]
I edited my comments, nice concepts
strip out the mac meta files, DStore etc, they are rejected

**Comment by vrindajain** [comment]
Done that, can you check again now?

**Comment by hectorkambow** [comment]
@vrindajain please be sure to include the changes suggested by Nicholas 👍 
Thank you - once those changes have been included we can go ahead and publish. 🚀

**Comment by vrindajain** [comment]
@hectorkambow I have updated the changes. Can't wait to see it up 🤩

**Comment by ninjaginja** [comment]
@vrindajain The readability of this article is still rough and could use some attention. Some of the word selection is off and general sentence/paragraph structure needs work. I'd suggest using an editing tool like [Hemingway](http://www.hemingwayapp.com/), or asking one of your peers to review the article.

**Comment by vrindajain** [comment]
Hey, @ninjaginja I'll take up a revision of the article and get back. Thanks.

**Comment by hectorkambow** [comment]
closing due to inactivity - can be re-opened at any time 🚀 
@vrindajain

**Pull request closed without merging**
