### PR TITLE
Create React CLI applications

### LINKED ISSUE #546: Creating Command Line Interface (CLI) applications using React.Js
### Brief Summary: 
CLI applications using Node.js are amazing and very easy to make. I did an article on how to do that [here](https://www.section.io/engineering-education/create-a-nodejs-cli/). The more CLI applications become popular, the more the need for them to be better, more responsive and contain more detail. With react, you can create good looking CLI's with styling and even render images. In this article, that is exactly what we will look at. 

### Key Takeaways: 

- The core difference between using Node.js and React.js. 
- Getting started with building good looking components and rendering them to the terminal.
- Why you should use React.js 
- Examples of popular applications and companies already using React.js for their CLI apps
- Using React INK to render components on the terminal.
- Build a simple application with React.js and React INK

### References: 
1. Vadimdemedes/ink. Retrieved October 28, 2020, from https://github.com/vadimdemedes/ink
2. Couriol, B. (2020, August 05). Interactive Terminal Apps with Ink 3 - New Built-In Hooks, Suspense and React Dev Tool Support. Retrieved October 28, 2020, from https://www.infoq.com/news/2020/08/ink3-hooks-devtool-terminal-apps/

### PR DESCRIPTION
**Pull request by katungi**
#### Preliminary Checks - Formatting and Structure 
- [x] Does your article follow any of the suggested structure formats? - **see [example formats](https://github.com/section-io/engineering-education/blob/master/CONTRIBUTING.md#example-format-structure)**
- [x] Is your article properly formatted in Markdown? - **see [Github Markdown guide](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet)**
- [x] Have you used the correct folder and file structure? - **see [Contribution Guidelines](https://github.com/section-io/engineering-education/blob/master/CONTRIBUTING.md)**
- [x] Is your article over 750 words? - **Tool**: [Wordcounter.net](https://wordcounter.net)
- [x] Have you used our preferred heading structure? - **[H3 (###) and up](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet#headers)**
- [x] Does your article provide enough value and detail about your topic? - **Articles should be clear, accurate, and fully explained.**
- [x] Can your article be understood by beginners? - **Assume the audience is smart but has no prior exposure to the common terminology in your article.**
- [x] Have you included a hero image that is 600x400 pixels and have the copyright to use it? - **Tools:** [Pixlr Image Editor](https://pixlr.com/e) for resizing and [Unsplash](https://unsplash.com) for Creative Commons images
- [x] In your PR - add a comment that states **["This fixes #(enter your Idea Content Form #)"](https://youtu.be/TKJ4RdhyB5Y?t=278)** to link and close your Idea Content (issue) when the PR is merged.
      

#### Grammar Checks
- [x] Have you spellchecked and grammar checked your article? - **Tool:** [Grammarly](https://grammarly.com)
- [x] Have you checked your article for readability? - **Tool:** [Hemmingway](http://www.hemingwayapp.com)
- [x] Have you added sources for quotes and images that aren't yours?

#### Technical Checks
- [x] Are your code snippets properly formatted for syntax highlighting - **see [Syntax guide](https://gohugo.io/content-management/syntax-highlighting)**

### Contribution Guidelines
For first-time contributors and for more details, **see [Contributing Guidelines](https://github.com/section-io/engineering-education/blob/master/CONTRIBUTING.md)**

This fixes #546

### CODE REVIEW

**Comment by hectorkambow** [comment]
plagiarism check done

**Review by LinusMuema — COMMENTED** [review]
Hi @katungi 
This is a really awesome article. Sorry it took a while to be reviewed; some issues with my code editor. I have one comment; it seems the article needs someone to have some experience with the React framework and Javascript skills; it would be really awesome to add the prerequisites section. This would make sure that people know what to expect. Just that, then we move to the tech review. 🙂🙂🙂

**Comment by hectorkambow** [comment]
NOTE: author pinged via Slack

**Comment by katungi** [comment]
@LinusMuema I will make the changes asap. Thanks for the review

**Comment by LinusMuema** [comment]
Hello @katungi 
I have done a technical review and a few things I have noted.
* Once you run the command `section-example`, you get a *`section-example: command not found`* error. Maybe this is because of the difference in OS, but it would be nice to inform people of this or even result in `node cli`, which works. You can add it as a script to help readers run the application
* The tests written in the app are actually not passing. I know it was not mentioned in the article, but it is also good to check on them. 🙂 🙃

**Comment by katungi** [comment]
I will work on the changes asap.
I hadn't thought about the difference in OS..I'll look Into that

**Review by LinusMuema — COMMENTED** [review]
Awesome job @katungi 
This article is good to go. Hey @hectorkambow, could you give this article a final review before publishing.

**Pull request merged**
