### PR TITLE
Article: Popular Data Science Libraries in python

### PR DESCRIPTION
**Pull request by Richu98**
This is article is all about the popular data science libraries in python.

### CODE REVIEW

**Comment by hectorkambow** [comment]
Good afternoon @lcaballero -  could you please give this article a tech review when you get a chance. Please & Thank you 🚀

**Comment by lcaballero** [comment]
This is a hard topic to discuss with a simple pass over libraries.  Very hard to determine what should be the purpose of an article like this or why some one would want to read it too.  Is it just to get an overview of the tools/libs for data scientists?  Could that be a bullet list?  @hectorkambow 

Would there need to be an opinion on these tools or some reason why there are so many?  Or at least why they are popular?  I'm not sure I'd get anything out of this article that finding an 'awesome' page wouldn't be a better source.

**Comment by Richu98** [comment]
What all changes I should make apart from the suggested changes @hectorkambow ?

**Comment by hectorkambow** [comment]
> What all changes I should make apart from the suggested changes @hectorkambow ?

@Richu98  - if you've included the changes above - it might help to add a conclusion (if you haven't already) to tie in the article - explain to the audience the why behind the information they are reading - what value it adds to their coding experiences -
How does knowing about these Data Science libraries in python help them out - how do they compare with other libraries - and in what situations (real world cases) are they used or helpful.

**Comment by Richu98** [comment]
> This is a hard topic to discuss with a simple pass over libraries. Very hard to determine what should be the purpose of an article like this or why some one would want to read it too. Is it just to get an overview of the tools/libs for data scientists? Could that be a bullet list? @hectorkambow
> 
> Would there need to be an opinion on these tools or some reason why there are so many? Or at least why they are popular? I'm not sure I'd get anything out of this article that finding an 'awesome' page wouldn't be a better source.

Thanks for the suggestion @lcaballero

**Comment by Richu98** [comment]
@hectorkambow  I have updated the article. Please Review

**Comment by Richu98** [comment]
image
Hey @hectorkambow 
Can you correct this line which I highlighted to **know the things**.
Sorry for the mistake I missed it. Please correct the article

**Pull request merged**
