### PR TITLE
build-a-websocket-powered-tic-tac-toe-with-adonisjs

### LINKED ISSUE #969: Build a Websockets Powered Tic-tac-toe with AdonisJS
### Brief Summary: 
Learn how web sockets work and how they are used in the real world by building Tic-tac-toe. Web sockets enable real-time communication in web applications. AdonisJS, a Node.js framework, has first-class support for web sockets. Tic-tac-toe is a simple I/O (Input/Output) application, so AdonisJS is a good fit for building it.

### Key Takeaways: 
1. How web sockets work
2. How cookies can be used to store socket ids
3. Best practices in designing socket-based applications

### References: 
1. https://developer.mozilla.org/en-US/docs/Web/API/WebSockets_API
2. https://medium.com/@td0m/what-are-web-sockets-what-about-rest-apis-b9c15fd72aac

### PR DESCRIPTION
**Pull request by vicradon**
build a websocket powered tic-tac-toe with adonisjs

#### Preliminary Checks - Formatting and Structure 
- [x] Does your article follow any of the suggested structure formats? - **see [example formats](https://github.com/section-io/engineering-education/blob/master/CONTRIBUTING.md#example-format-structure)**
- [x] Is your article properly formatted in Markdown? - **see [Github Markdown guide](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet)**
- [x] Have you used the correct folder and file structure? - **see [Contribution Guidelines](https://github.com/section-io/engineering-education/blob/master/CONTRIBUTING.md)**
- [x] Is your article over 750 words? - **Tool**: [Wordcounter.net](https://wordcounter.net)
- [x] Have you used our preferred heading structure? - **[H3 (###) and up](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet#headers)**
- [x] Does your article provide enough value and detail about your topic? - **Articles should be clear, accurate, and fully explained.**
- [x] Can your article be understood by beginners? - **Assume the audience is smart but has no prior exposure to the common terminology in your article.**
- [x] Have you included a hero image that is 600x400 pixels and have the copyright to use it? - **Tools:** [Pixlr Image Editor](https://pixlr.com/e) for resizing and [Unsplash](https://unsplash.com) for Creative Commons images
- [x] In your PR - add a comment that states **["This fixes #(enter your Idea Content Form #)"](https://youtu.be/TKJ4RdhyB5Y?t=278)** to link and close your Idea Content (issue) when the PR is merged.

**NOTE: (1st time contributors - submit ONLY one article to get familiar with the process and style-once published, you can then submit any number of articles.)**
      
#### Grammar Checks
- [x] Have you spellchecked and grammar checked your article? - **Tools:** [Write&Improve](https://writeandimprove.com/?lang=en-GB) - [ProWritingAid](https://prowritingaid.com/) -  [Grammarly](https://grammarly.com) 
- [x] Have you checked your article for readability? - **Tool:** [Hemmingway](http://www.hemingwayapp.com)
- [x] Have you added sources for quotes and images that aren't yours?

#### Technical Checks
- [x] Are your code snippets properly formatted for syntax highlighting - **see [Syntax guide](https://gohugo.io/content-management/syntax-highlighting)**

### Contribution Guidelines
For first-time contributors and for more details, **see [Contributing Guidelines](https://github.com/section-io/engineering-education/blob/master/CONTRIBUTING.md)**

This fixes #969

### CODE REVIEW

**Comment by zolomohan** [comment]
@vicradon Please update the PR Title with the Article's Title.

**Comment by vicradon** [comment]
Hi @zolomohan 
I've changed the PR title.

**Comment by hectorkambow** [comment]
👋 Thank you for submitting this PR - we will review it ASAP - all PRs go into our queue will be looked over before being approved to be published.

**Comment by ReactifyStudio** [comment]
@hectorkambow regarding the peer reviewer position I applied, I would like to start reviewing this article. It fits with my Javascript stack.

**Comment by ReactifyStudio** [comment]
Hi, @vicradon I noticed a lot of grammatical errors. Some sentences should be written more precisely. Consider running the article through Grammarly and Hemmingway once. Also, link your images using: name. You need to point to the engineering-education repo rather than your forked version. Please check all the instances.

**Comment by ReactifyStudio** [comment]
You are using the `href` tags to link the images. It seems you need to study the markdown syntax a bit. Check out this[ cheat sheet]
(https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet) for reference. Kindly correct all matching instances.

**Comment by vicradon** [comment]
@ReactifyStudio, thank you for reviewing this article. I have run the article through Grammarly and Hemmingwayapp and corrected the highlighted issues. I have also appended `/engineering-education/`  to all image URLs.

**Comment by paulodhiambo** [comment]
@vicradon, please make the changes as I want to head to a tech reviewer before this is ready for final review.

**Comment by ReactifyStudio** [comment]
@vicradon  please make the changes and this article I will head over to tech review and finally final review. It's already an easy to follow through. Just the minor stuffs

**Comment by ReactifyStudio** [comment]
@vicradon it seems you are not using the `### Turn Logic` in your markdown`? I have gone through the code and it's working flawlessly. Please change this. @hectorkambow this is ready for the final review.

**Comment by hectorkambow** [comment]
plagiarism check done

**Comment by hectorkambow** [comment]
@vicradon  Great article 👍  

cc; @ReactifyStudio  🚀

**Pull request merged**
