### PR TITLE
Blockchain: As a revolution in healthcare

### PR DESCRIPTION
**Pull request by Jethro-magaji**
This is an article on the importance of blockchain technology in healthcare and its implementations.

### CODE REVIEW

**Comment by hectorkambow** [comment]
@Jethro-magaji 👋  good afternoon Jethro - it appears your repo may not be updated - as your article is not showing up correctly. I'd recommend doing a pull (updating) your branched repo and that should fix/format things correctly.

**Comment by Jethro-magaji** [comment]
Thanks for the info, I will make the adjustments.

**Comment by Jethro-magaji** [comment]
Hello, I just made some changes now, please notify me if it worked. Thanks

**Comment by Jethro-magaji** [comment]
An article on the history, basics, and use cases of nodejs.

**Comment by hectorkambow** [comment]
@Jethro-magaji - I noticed that there is more than one article on this PR - if you could ensure that you are branching from the master - when you create a new PR. 
Also, please make sure your fork is updated to the latest EngEd repo. 🚀

**Comment by hectorkambow** [comment]
Moved to this [PR](https://github.com/section-io/engineering-education/pull/231/files)

**Pull request closed without merging**
