### PR TITLE
Getting started with Docker

### PR DESCRIPTION
**Pull request by damikanye**
Understanding how to install Docker, creating your first image from Dockerhub and how to create a Dockerfile.

### CODE REVIEW

**Comment by hectorkambow** [comment]
Good afternoon 👋 @ivan-section-io 🚀 - wanted to ask if you could give this article a tech review as well - whenever you have a moment before we publish.
Thank you

**Comment by ninjaginja** [comment]
@damikanye When running this article through our third-party content detector, much of the copy in this article appears to be directly taken from third-party sources. When we see vertabim paragraphs and excerpts from other authors, we take it very seriously. We'll need to ask you to rewrite any 'borrowed' content, and properly cite sources throughout the article with quotes/links.

**Comment by damikanye** [comment]
Okay will work on that

**Comment by hectorkambow** [comment]
closing due to inactivity - can be re-opened at any time to continue 🚀 
@damikanye

**Comment by hectorkambow** [comment]
@damikanye - thank you for the recent changes. 
We re-ran your article in our 3rd party software and it raised a few red flags (please see attached) 
and address any sentences that were underlined - and code that need to be included (that's fine) 
But any content that is explaining the technical parts should be original content. 
[docker_article_check_cisca.pdf](https://github.com/section-io/engineering-education/files/5125799/docker_article_check_cisca.pdf)

**Pull request merged**
