### PR TITLE
Why data scientists need to move from jupyter notebooks to scripts

### PR DESCRIPTION
**Pull request by EKahuha**
#### Preliminary Checks - Formatting and Structure 
- [x] Does your article follow any of the suggested structure formats? see the example [Formats here](https://github.com/section-io/engineering-education/blob/master/CONTRIBUTING.md#example-format-structure)
- [x] Is your article properly formatted in Markdown? - see [Github Markdown guide](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet)
- [x] Have you used the correct folder and file structure? - see [Contribution Guidelines](https://github.com/section-io/engineering-education/blob/master/CONTRIBUTING.md)
- [x] Is your article over 750 words?
- [x] Have you used our preferred heading structure? - [H3 (###) and up](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet#headers)
- [x] Does your article provide enough value and detail about your topic? Articles should be clear, accurate, and fully explained.
- [x] Can your article be understood by beginners? **Assume the audience is smart but has no prior exposure to the common terminology in your article.**
- [x] Have you included a hero image? (600X400 pixels (images can be resized in paint) - also please make sure the image is from a site like www.unsplash.com)
- [ ] In your PR - add a comment that states ["This fixes #(enter your Idea Content Form #)"](https://youtu.be/TKJ4RdhyB5Y?t=278) to link and close your Idea Content (issue) when the PR is merged.
      

#### Grammar Checks
- [x] Have you spellchecked and grammar checked your article? - Tool: [Grammarly](https://grammarly.com)
- [x] Have you checked your article for readability? - Tool: [Hemmingway](http://www.hemingwayapp.com/)
- [x] Have you added sources for quotes and images that aren't yours?

### Technical Checks
- [x] Are your code snippets properly formatted for syntax highlighting - see [Syntax guide](https://gohugo.io/content-management/syntax-highlighting/)
- [x] Have you used Repl.it for your code snippets?

### Contribution Guidelines
For first-time contributors and for more details, see [Contributing Guidelines](https://github.com/section-io/engineering-education/blob/master/CONTRIBUTING.md)

### CODE REVIEW

**Comment by EKahuha** [comment]
Hi @hectorkambow  I have done the revision by changing some content.

**Comment by hectorkambow** [comment]
@EKahuha  👋  Good morning Eric - was going through your Notebook article -seems very informative - but going through it I couldn't help but think the code snippet examples you included (as screenshots) those would be add more value to the reader if they were actual code snippets in the article that they could copy for their projects.
If you could add the examples as code snippets - after that your article should be ready for a tech review 🚀  
Thank you

**Comment by hectorkambow** [comment]
You can also use repli.it links to showcase the code running @EKahuha

**Comment by EKahuha** [comment]
Hello @hectorkambow, - code snippets added.

**Comment by hectorkambow** [comment]
👋  Good afternoon @kurt-sectionio 
Happy Monday 
Wanted to ask if you could give this "jupyter notebooks to scripts" article a tech review whenever you have a moment. 
🚀

**Review by kurt-sectionio — CHANGES_REQUESTED** [review]
This is very good. 

Is "Hhydra.cc" a typo in line 86?

You appear to use "data engineer" and "data scientist" as exchangeable terms, but I think they are quite different and I wouldn't expect data engineers to use Jupyter Notebooks. Please change all references to "data engineers" to "data scientists".

**Comment by EKahuha** [comment]
Changes made @kurt-sectionio 
Thank you.

**Review by kurt-sectionio — APPROVED** [review]
Thanks. Line 91 needs "scientists"

**Pull request merged**
