### PR TITLE
Breaking Down Kafka vs. Pulsar

### LINKED ISSUE #502: Breaking Down Apache Pulsar vs Kafka
### Brief Summary: 
Describe the what, why, and how of your content idea in 2-5 sentences.
The options for application-to-application communication have grown exponentially, including the addition of several very powerful open source solutions. Apache Pulsar is an open-source multi-tenant, high-performance messaging solution. Apache Pulsar is a fast-growing alternative to Kafka. 
### Key Takeaways: 
What are the 3-5 most important things the reader should understand or be able to do after reading this article?
1. Overview of apache pulsar
2. Architecture 
3. Geo-Replication
4. Use cases 
5. Apache Pulsar or Apache Kafka: which is better? 

### References: 
Please list links to any published content/research that you intend to use to support/guide this article. (If none, please indicate 'N/A'.)
N/A

### PR DESCRIPTION
**Pull request by EKahuha**
this fixes #502

#### Preliminary Checks - Formatting and Structure 
- [x] Does your article follow any of the suggested structure formats? - **see [example formats](https://github.com/section-io/engineering-education/blob/master/CONTRIBUTING.md#example-format-structure)**
- [x] Is your article properly formatted in Markdown? - **see [Github Markdown guide](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet)**
- [x] Have you used the correct folder and file structure? - **see [Contribution Guidelines](https://github.com/section-io/engineering-education/blob/master/CONTRIBUTING.md)**
- [x] Is your article over 750 words? - **Tool**: [Wordcounter.net](https://wordcounter.net)
- [x] Have you used our preferred heading structure? - **[H3 (###) and up](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet#headers)**
- [x] Does your article provide enough value and detail about your topic? - **Articles should be clear, accurate, and fully explained.**
- [x] Can your article be understood by beginners? - **Assume the audience is smart but has no prior exposure to the common terminology in your article.**
- [x] Have you included a hero image that is 600x400 pixels and have the copyright to use it? - **Tools:** [Pixlr Image Editor](https://pixlr.com/e) for resizing and [Unsplash](https://unsplash.com) for Creative Commons images
- [x] In your PR - add a comment that states **["This fixes #(enter your Idea Content Form #)"](https://youtu.be/TKJ4RdhyB5Y?t=278)** to link and close your Idea Content (issue) when the PR is merged.
      

#### Grammar Checks
- [x] Have you spellchecked and grammar checked your article? - **Tool:** [Grammarly](https://grammarly.com)
- [x] Have you checked your article for readability? - **Tool:** [Hemmingway](http://www.hemingwayapp.com)
- [x] Have you added sources for quotes and images that aren't yours?

#### Technical Checks
- [x] Are your code snippets properly formatted for syntax highlighting - **see [Syntax guide](https://gohugo.io/content-management/syntax-highlighting)**

### Contribution Guidelines
For first-time contributors and for more details, **see [Contributing Guidelines](https://github.com/section-io/engineering-education/blob/master/CONTRIBUTING.md)**

### CODE REVIEW

**Comment by hectorkambow** [comment]
Plagiarism check done

**Comment by hectorkambow** [comment]
@EKahuha 
Thank you for submitting another great article. 
Learning much about Kafka and Pulsar. 

Just finished going over you article and wanted to add some extra information to make it easier to follow. 

A prerequisite section would help any reader to know what they need to know before jumping into your article. 

Your article assumes much knowledge from the reader - you speak about concepts without explaining what they are. 

A term section would also be helpful for the audience to follow along. 

You speak about consumer, topics, brokers, etc all without considering if the reader knows what you are referring to. 

I say this often but it really helps - assume the reader is smart - but has NO BACKGROUND on the topic you are discussing. 

Please add some more detail explaining these ideas - that would be very helpful for the EngEd community as a whole. 

The links were great thank you - I added more. 

Also as a rule of thumb - if there is a related EngEd article - try to include it into your articles as a reference. 

Hope this helps.

**Comment by hectorkambow** [comment]
NOTE: author pinged via Slack

**Comment by EKahuha** [comment]
@hectorkambow I have updated the article.

**Pull request merged**
