### PR TITLE
Node Heroku Deployment

### PR DESCRIPTION
**Pull request by LinusMuema**
This is an article about deploying a NodeJS app to Heroku and the other small processes involved.
The files added are:
`hero.jpg`,
`atlas-connect.png`
`atlas-ip.png`
`atlas-url.png`
`cluster.png`
`package-json.png`

### CODE REVIEW

**Comment by hectorkambow** [comment]
@pavelnikolov if you could give this article a review when you have a moment? 🚀

**Comment by ninjaginja** [comment]
@LinusMuema Our article review committee had some internal discussion around how to handle content that strongly incorporates competitive products. (Heroku has competitive product offerings to Section.) While our goal is to present unbiased content in the EngEd forum, we don't want to actively push competitive products. If you can find a way to remove the Heroku deployment portion from the article, please do so. However, if this is too fundamental to the overall content, then I understand, and we'll simply close this PR. (Of course you're welcome to publish this content to forums outside of Section, if you wish.)

**Comment by LinusMuema** [comment]
@ninjaginja I understand. It was playing a major role in the article but thanks for the feedback. I will continue to suggest more articles.

**Comment by ninjaginja** [comment]
Thanks for understanding @LinusMuema. Keep up the great articles coming in! I'll go ahead and close this PR for now.

**Pull request closed without merging**
