### PR TITLE
How to create an API using Laravel

### LINKED ISSUE #652: How to create an API using Laravel
### Brief Summary: 
Laravel is a PHP framework that make it easy for users to build high quality web applications. Laravel is preferred by many developers since it contains close to all required dependencies. It also eliminates a lot of boiler plate code. It is, therefore, easy to create APIs using this framework.

### Key Takeaways: 
 - Understand what APIs are
- Create a simple API using Laravel
- Debug errors that occur during compilation

### References: 
https://laravel.com/

### PR DESCRIPTION
**Pull request by WanjaMIKE**
This fixes  #652 

#### Preliminary Checks - Formatting and Structure 
- [x] Does your article follow any of the suggested structure formats? - **see [example formats](https://github.com/section-io/engineering-education/blob/master/CONTRIBUTING.md#example-format-structure)**
- [x] Is your article properly formatted in Markdown? - **see [Github Markdown guide](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet)**
- [x] Have you used the correct folder and file structure? - **see [Contribution Guidelines](https://github.com/section-io/engineering-education/blob/master/CONTRIBUTING.md)**
- [x] Is your article over 750 words? - **Tool**: [Wordcounter.net](https://wordcounter.net)
- [x] Have you used our preferred heading structure? - **[H3 (###) and up](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet#headers)**
- [x] Does your article provide enough value and detail about your topic? - **Articles should be clear, accurate, and fully explained.**
- [x] Can your article be understood by beginners? - **Assume the audience is smart but has no prior exposure to the common terminology in your article.**
- [x] Have you included a hero image that is 600x400 pixels and have the copyright to use it? - **Tools:** [Pixlr Image Editor](https://pixlr.com/e) for resizing and [Unsplash](https://unsplash.com) for Creative Commons images
- [x] In your PR - add a comment that states **["This fixes #(enter your Idea Content Form #)"](https://youtu.be/TKJ4RdhyB5Y?t=278)** to link and close your Idea Content (issue) when the PR is merged.

**NOTE: (1st time contributors - submit ONLY one article to get familiar with the process and style-once published, you can then submit any number of articles.)**
      
#### Grammar Checks
- [x] Have you spellchecked and grammar checked your article? - **Tools:** [Write&Improve](https://writeandimprove.com/?lang=en-GB) - [ProWritingAid](https://prowritingaid.com/) -  [Grammarly](https://grammarly.com) 
- [x] Have you checked your article for readability? - **Tool:** [Hemmingway](http://www.hemingwayapp.com)
- [x] Have you added sources for quotes and images that aren't yours?

#### Technical Checks
- [x] Are your code snippets properly formatted for syntax highlighting - **see [Syntax guide](https://gohugo.io/content-management/syntax-highlighting)**

### Contribution Guidelines
For first-time contributors and for more details, **see [Contributing Guidelines](https://github.com/section-io/engineering-education/blob/master/CONTRIBUTING.md)**

This fixes #652

### CODE REVIEW

**Comment by WanjaMIKE** [comment]
fixes #652

**Comment by hectorkambow** [comment]
👋 Thank you for submitting this PR - we will review it ASAP - all PRs go into our queue will be looked over before being approved to be published.

**Review by kayere — APPROVED** [review]
Great article @WanjaMIKE. I have noticed a great improvement in grammar. Keep up the great work.

**Comment by hectorkambow** [comment]
[How to create an API using Laravel #750.pdf](https://github.com/section-io/engineering-education/files/5661444/How.to.create.an.API.using.Laravel.750.pdf)
👋  
Good afternoon @WanjaMIKE  
Thank you for submitting your "How to create an API using Laravel" article - upon running it through our 3rd party plagiarism checker it raised a few red flags and the % was bit higher than we typically like to see. 

Please see attached PDF to see the underlined areas to see what sections may need extra sources - and for code snippets - we would recommend using brand new original or unique code snippets. 
👍  
Thank you 🚀

**Comment by WanjaMIKE** [comment]
@hectorkambow 

I have made appropriate changes to remove plagiarism. I also realized that the plagiarism checker flagged certain statements that are usually generated by the framework. Any modification to these statements will lead to errors.
Such as
use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;

Thanks

**Pull request merged**
