### PR TITLE
All about fragments in android applications

### LINKED ISSUE #852: All about fragments in android applications
### Brief Summary: 
Fragments are simply independent android components that can be used in activities. Though a fragment runs in an activity, it has its own lifecycle and layout.

### Key Takeaways: 
 - Understand what are fragments
 - Know how to use fragments in android 
 - Debug errors in the implementation of fragments.

### References: 

https://developer.android.com/guide/fragments

### PR DESCRIPTION
**Pull request by WanjaMIKE**
This fixes #852

#### Preliminary Checks - Formatting and Structure 
- [x] Does your article follow any of the suggested structure formats? - **see [example formats](https://github.com/section-io/engineering-education/blob/master/CONTRIBUTING.md#example-format-structure)**
- [x] Is your article properly formatted in Markdown? - **see [Github Markdown guide](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet)**
- [x] Have you used the correct folder and file structure? - **see [Contribution Guidelines](https://github.com/section-io/engineering-education/blob/master/CONTRIBUTING.md)**
- [x] Is your article over 750 words? - **Tool**: [Wordcounter.net](https://wordcounter.net)
- [x] Have you used our preferred heading structure? - **[H3 (###) and up](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet#headers)**
- [x] Does your article provide enough value and detail about your topic? - **Articles should be clear, accurate, and fully explained.**
- [x] Can your article be understood by beginners? - **Assume the audience is smart but has no prior exposure to the common terminology in your article.**
- [x] Have you included a hero image that is 600x400 pixels and have the copyright to use it? - **Tools:** [Pixlr Image Editor](https://pixlr.com/e) for resizing and [Unsplash](https://unsplash.com) for Creative Commons images
- [x] In your PR - add a comment that states **["This fixes #(enter your Idea Content Form #)"](https://youtu.be/TKJ4RdhyB5Y?t=278)** to link and close your Idea Content (issue) when the PR is merged.

**NOTE: (1st time contributors - submit ONLY one article to get familiar with the process and style-once published, you can then submit any number of articles.)**
      
#### Grammar Checks
- [x] Have you spellchecked and grammar checked your article? - **Tools:** [Write&Improve](https://writeandimprove.com/?lang=en-GB) - [ProWritingAid](https://prowritingaid.com/) -  [Grammarly](https://grammarly.com) 
- [x] Have you checked your article for readability? - **Tool:** [Hemmingway](http://www.hemingwayapp.com)
- [x] Have you added sources for quotes and images that aren't yours?

#### Technical Checks
- [x] Are your code snippets properly formatted for syntax highlighting - **see [Syntax guide](https://gohugo.io/content-management/syntax-highlighting)**

### Contribution Guidelines
For first-time contributors and for more details, **see [Contributing Guidelines](https://github.com/section-io/engineering-education/blob/master/CONTRIBUTING.md)**

### CODE REVIEW

**Comment by hectorkambow** [comment]
👋 Thank you for submitting this PR - we will review it ASAP - all PRs go into our queue will be looked over before being approved to be published.

**Review by kayere — COMMENTED** [review]
Hey @WanjaMIKE. I have just gone through your article. It is looking good so far. However, I feel like you have not explained a lot about fragments(as your title suggests). You have given more details about navigation which has been covered in another article. I'd suggest you give the reader what he/she is expecting. Please write more about the functions associated with fragments, the fragment lifecycle etc. Also, explain your code snippets.

**Comment by WanjaMIKE** [comment]
Hey @kayere 

I have written more about fragments and explained the code snippets through inline comments

**Review by kayere — APPROVED** [review]

**Comment by hectorkambow** [comment]
plagiarism check done

**Comment by hectorkambow** [comment]
@WanjaMIKE Great tutorial  - really informative and well written. 
Please go over the minor edits I made to see what can be applied to future article - made a few minor changes to help the article flow a bit better. 

One main thing I'd like to point out was the image used that had an outside link - this is a major thing we should avoid and correct if we see any other student doing it. 

Best practice is to have the image hosted on our site and of course provide sources if needed 👍  (i already added it just an FYI)

CC: @kayere

**Comment by WanjaMIKE** [comment]
@hectorkambow 
Noted. Thank you

**Pull request merged**
