### PR TITLE
Article Intro to Webpack

### PR DESCRIPTION
**Pull request by rohanreddych**
add logo/hero img at top

### CODE REVIEW

**Comment by hectorkambow** [comment]
Good afternoon Gary @gwritz  👋 
Wanted to ask if you could give this article a tech review whenever you are free.
Thank you 🚀

**Comment by ninjaginja** [comment]
@rohanreddych There appear to be many sentences in this article that are taken verbatim from third-party sources. We can't publish any content that is not original or properly cited/referenced. There are many free online tools where you can check this (such as [quetext.com](https://www.quetext.com/), and if you're uncertain about the definitions around plagiarism, this is a [good resource to reference](https://www.scribbr.com/category/plagiarism/.

**Comment by rohanreddych** [comment]
@ninjaginja I added citations and added/changed some content. I could not share the report as pdf.

**Comment by ninjaginja** [comment]
Thanks @rohanreddych, much better!

**Pull request merged**
