### PR TITLE
Android Application In-app Update Using Android Studio

### LINKED ISSUE #678: Implement Android Application Update
### Brief Summary: 
Once an application is deployed to the production environment, the first release becomes the first version of that application. But in the future, the application may require enhancements, and more features will be added to it. These features are updates that will frequently be used to improve the application. Every time a new update is made, that triggers a new version. 

Suppose an android user has your application installed on their mobile phone. In that case, the only way to get the new updated features is by updating the installed application to the latest version. 

Google notifies android use that some applications need updates ( some users turn auto-update on), which is excellent, but you want to keep all your users up to date with the latest new released version.

As a developer, we always want our users to update the latest version as soon as we release new features. You want everyone to have the latest version installed, and you want them to use the latest features you’ve developed.

This guide will walk the reader on how to implement that using android studio. 

### Key Takeaways: 
This guide will go over two main streams to implement application updates.

- Force the user to update the application. I.e., a case where an update dialog will always show up whenever the user opens the application until the user updates the newly released version.

- Using google in-app update API.

### References: 
Please list links to any published content/research that you intend to use to support/guide this article. (If none, please indicate 'N/A'.)

### PR DESCRIPTION
**Pull request by kimkimani**
#### Preliminary Checks - Formatting and Structure 
- [x] Does your article follow any of the suggested structure formats? - **see [example formats](https://github.com/section-io/engineering-education/blob/master/CONTRIBUTING.md#example-format-structure)**
- [x] Is your article properly formatted in Markdown? - **see [Github Markdown guide](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet)**
- [x] Have you used the correct folder and file structure? - **see [Contribution Guidelines](https://github.com/section-io/engineering-education/blob/master/CONTRIBUTING.md)**
- [x] Is your article over 750 words? - **Tool**: [Wordcounter.net](https://wordcounter.net)
- [x] Have you used our preferred heading structure? - **[H3 (###) and up](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet#headers)**
- [x] Does your article provide enough value and detail about your topic? - **Articles should be clear, accurate, and fully explained.**
- [x] Can your article be understood by beginners? - **Assume the audience is smart but has no prior exposure to the common terminology in your article.**
- [x] Have you included a hero image that is 600x400 pixels and have the copyright to use it? - **Tools:** [Pixlr Image Editor](https://pixlr.com/e) for resizing and [Unsplash](https://unsplash.com) for Creative Commons images
- [x] In your PR - add a comment that states **["This fixes #(enter your Idea Content Form #)"](https://youtu.be/TKJ4RdhyB5Y?t=278)** to link and close your Idea Content (issue) when the PR is merged.

**NOTE: (1st time contributors - submit ONLY one article to get familiar with the process and style-once published, you can then submit any number of articles.)**
      
#### Grammar Checks
- [x] Have you spellchecked and grammar checked your article? - **Tools:** [Write&Improve](https://writeandimprove.com/?lang=en-GB) - [ProWritingAid](https://prowritingaid.com/) -  [Grammarly](https://grammarly.com) 
- [x] Have you checked your article for readability? - **Tool:** [Hemmingway](http://www.hemingwayapp.com)
- [ ] Have you added sources for quotes and images that aren't yours?

#### Technical Checks
- [x] Are your code snippets properly formatted for syntax highlighting - **see [Syntax guide](https://gohugo.io/content-management/syntax-highlighting)**

### Contribution Guidelines
For first-time contributors and for more details, **see [Contributing Guidelines](https://github.com/section-io/engineering-education/blob/master/CONTRIBUTING.md)**
FIXES #678

### CODE REVIEW

**Comment by hectorkambow** [comment]
👋 Thank you for submitting this PR - we will review it ASAP - all PRs go into our queue will be looked over before being approved to be published.

**Comment by WanjaMIKE** [comment]
@kimkimani 

Hey, good work on the article. I have learned a lot about pushing app updates. I have made several minor changes in the article.
Could clarify if its onCreate or Ocreate in the statement below.

Add the following code just below the `appUpdateManager` instance created on the `Ocreate` method.

Also, could you please go through the article and shorten certain sentences, then we will proceed to the tech review. Nice Work.

**Comment by hectorkambow** [comment]
Pinged via Slack

**Comment by kimkimani** [comment]
@WanjaMIKE I think readability will take a hit as shown by the Hemingway editor because of the many technical terms incorporated within the sentence flow.

**Comment by kimkimani** [comment]
> @kimkimani
> 
> Hey, good work on the article. I have learned a lot about pushing app updates. I have made several minor changes in the article.
> Could clarify if its onCreate or Ocreate in the statement below.
> 
> Add the following code just below the `appUpdateManager` instance created on the `Ocreate` method.
> 
> Also, could you please go through the article and shorten certain sentences, then we will proceed to the tech review. Nice Work.

@WanjaMIKE Check the newly updated commits

**Review by WanjaMIKE — APPROVED** [review]
@kimkimani 
Nice article. Easy to follow. Provided code snippets work as required. Good work.

**Pull request merged**
