### PR TITLE
Stochastic Gradient Descent Optimzed Linear Classifier in Python

### LINKED ISSUE #462: Stochastic Gradient Descent Optimized Linear Classifier in Python
### Brief Summary: 
Describe the what, why, and how of your content idea in 2-5 sentences.
Stochastic gradient descent is an optimization algorithm used extensively across the field of machine learning and deep learning. We will build a linear classifier from scratch and understand the optimization process using the SGD optimizer.
### Key Takeaways: 
What are the 3-5 most important things the reader should understand or be able to do after reading this article?
1. Build linear classifier from scratch using SGD optimizer
2. Build SGD optimizer from scratch
3. Understand linear classifiers and their applications
### References: 
Please list links to any published content/research that you intend to use to support/guide this article. (If none, please indicate 'N/A'.)
N/A

### PR DESCRIPTION
**Pull request by lalith1403**
#### Preliminary Checks - Formatting and Structure 
- [x] Does your article follow any of the suggested structure formats? - **see [example formats](https://github.com/section-io/engineering-education/blob/master/CONTRIBUTING.md#example-format-structure)**
- [x] Is your article properly formatted in Markdown? - **see [Github Markdown guide](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet)**
- [x] Have you used the correct folder and file structure? - **see [Contribution Guidelines](https://github.com/section-io/engineering-education/blob/master/CONTRIBUTING.md)**
- [x] Is your article over 750 words? - **Tool**: [Wordcounter.net](https://wordcounter.net)
- [x] Have you used our preferred heading structure? - **[H3 (###) and up](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet#headers)**
- [x] Does your article provide enough value and detail about your topic? - **Articles should be clear, accurate, and fully explained.**
- [x] Can your article be understood by beginners? - **Assume the audience is smart but has no prior exposure to the common terminology in your article.**
- [x] Have you included a hero image that is 600x400 pixels and have the copyright to use it? - **Tools:** [Pixlr Image Editor](https://pixlr.com/e) for resizing and [Unsplash](https://unsplash.com) for Creative Commons images
- [x] In your PR - add a comment that states **["This fixes #(enter your Idea Content Form #)"](https://youtu.be/TKJ4RdhyB5Y?t=278)** to link and close your Idea Content (issue) when the PR is merged.
      

#### Grammar Checks
- [x] Have you spellchecked and grammar checked your article? - **Tool:** [Grammarly](https://grammarly.com)
- [x] Have you checked your article for readability? - **Tool:** [Hemmingway](http://www.hemingwayapp.com)
- [x] Have you added sources for quotes and images that aren't yours?

#### Technical Checks
- [x] Are your code snippets properly formatted for syntax highlighting - **see [Syntax guide](https://gohugo.io/content-management/syntax-highlighting)**
- [x] Have you used Repl.it for your code snippets?

This fixes #462 #462
### Contribution Guidelines
For first-time contributors and for more details, **see [Contributing Guidelines](https://github.com/section-io/engineering-education/blob/master/CONTRIBUTING.md)**

### CODE REVIEW

**Comment by lalith1403** [comment]
mathjax might need to be added. I don't have the code snippet. Kindly add the required script at the end of the file.

**Comment by hectorkambow** [comment]
plagiarism check done

**Comment by hectorkambow** [comment]
👋  Good afternoon @kurt-sectionio 
Wanted to ask if you wouldn't mind giving this "Stochastic Gradient Descent Optimized Linear Classifier in Python" tutorial a tech review whenever you have a moment. 
Thank you v much 🚀

**Review by kurt-sectionio — APPROVED** [review]
Looks good. Please address the points below:

Line 75: I wouldn't say it seeks minima (plural), or even a minimum (singular). It simply moves down the gradient. That simple logic will ensure it finds a minimum, local or global. Check occurrences of "minimum" and "minima" throughout to verify/correct when it should be plural or singular.

Line 83: "Minima" is the plural form of "minimum". You don't need to write "minimas". It is also confusing to say "larger minima", since "large" is the opposite of what you mean. Try: "smaller/deeper/more extreme minima" or something like that.

Line 179: The normalization method you describe in lines 181 will have mean 0 and variance 1, but the range is not (-1,1).

**Pull request closed without merging**
