### PR TITLE
How to build a UI for your model using Streamlit

### PR DESCRIPTION
**Pull request by rahulbanerjee26**
#### Preliminary Checks - Formatting and Structure 
-  [x]  Does your article follow any of the suggested structure formats? - **see [example formats](https://github.com/section-io/engineering-education/blob/master/CONTRIBUTING.md#example-format-structure)**
- [x] Is your article properly formatted in Markdown? - **see [Github Markdown guide](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet)**
- [x] Have you used the correct folder and file structure? - **see [Contribution Guidelines](https://github.com/section-io/engineering-education/blob/master/CONTRIBUTING.md)**
- [x] Is your article over 750 words? - **Tool**: [Wordcounter.net](https://wordcounter.net)
- [x] Have you used our preferred heading structure? - **[H3 (###) and up](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet#headers)**
- [x] Does your article provide enough value and detail about your topic? - **Articles should be clear, accurate, and fully explained.**
- [x] Can your article be understood by beginners? - **Assume the audience is smart but has no prior exposure to the common terminology in your article.**
- [x] Have you included a hero image that is 600x400 pixels and have the copyright to use it? - **Tools:** [Pixlr Image Editor](https://pixlr.com/e) for resizing and [Unsplash](https://unsplash.com) for Creative Commons images
- [x] In your PR - add a comment that states **["This fixes #(enter your Idea Content Form #)"](https://youtu.be/TKJ4RdhyB5Y?t=278)** to link and close your Idea Content (issue) when the PR is merged.

**NOTE: (1st time contributors - submit ONLY one article to get familiar with the process and style-once published, you can then submit any number of articles.)**
      
#### Grammar Checks
- [x] Have you spellchecked and grammar checked your article? - **Tools:** [Write&Improve](https://writeandimprove.com/?lang=en-GB) - [ProWritingAid](https://prowritingaid.com/) -  [Grammarly](https://grammarly.com) 
- [x] Have you checked your article for readability? - **Tool:** [Hemmingway](http://www.hemingwayapp.com)
- [x] Have you added sources for quotes and images that aren't yours?

#### Technical Checks
- [x] Are your code snippets properly formatted for syntax highlighting - **see [Syntax guide](https://gohugo.io/content-management/syntax-highlighting)**

### Contribution Guidelines
For first-time contributors and for more details, **see [Contributing Guidelines](https://github.com/section-io/engineering-education/blob/master/CONTRIBUTING.md)**

### CODE REVIEW

**Comment by rahulbanerjee26** [comment]
This Fixes Isuue #973

**Comment by rahulbanerjee26** [comment]
I wasn't sure how to add a hero image. I would like to add 'screencast.gif' as the hero image.

**Review by lalith1403 — APPROVED** [review]
Well written article. The flow of information is logical and the code works. Congratulations!

**Comment by lalith1403** [comment]
> I wasn't sure how to add a hero image. I would like to add 'screencast.gif' as the hero image.

I don't think you can add gifs as hero images. They have to belong to jpeg or png formats.

**Comment by lalith1403** [comment]
I notice that (since this is your 1st article) we will need a short bio blurb and headshot image to add towards the bottom of all your articles.

Please refer to any file in the [author ](https://github.com/section-io/engineering-education/tree/master/authors)folder in the repo as a guide.

You also need to add a hero image to the repository. You can use Unsplash to find thumbnail images.

**Comment by rahulbanerjee26** [comment]
Hi! @lalith1403  Thanks for reviewing! I have made the requested changes. However, I think I messed up the PR. Could you let me know the right way to make changes to an already existing PR or direct me to an article with more information? Thanks!

**Comment by lalith1403** [comment]
I think you have messed this PR. Can you take the latest updated file and create a duplicate PR? Let me know through the comment box once done.

**Comment by rahulbanerjee26** [comment]
Hey @lalith1403 , I have created a new PR. 
PR #1194 

Thanks!

**Comment by lalith1403** [comment]
@hectorkambow A new duplicate pr is created. Kindly note.

**Pull request closed without merging**
