### PR TITLE
Kotlin collections

### LINKED ISSUE #452: Kotlin collections
### Brief Summary: 
Kotlin has a rich and wide variety of collections. All of them have their own special properties and this article aims to demystify them. It will help new learners get familiar with them and some of their basic methods.

### Key Takeaways: 
1. What are Kotlin collections
2. Properties of Kotlin  Collections
3. Differences between various collections
4. Examples of Collection methods

### References: 
N/A

### PR DESCRIPTION
**Pull request by LinusMuema**
#### Preliminary Checks - Formatting and Structure 
- [x] Does your article follow any of the suggested structure formats? - **see [example formats](https://github.com/section-io/engineering-education/blob/master/CONTRIBUTING.md#example-format-structure)**
- [x] Is your article properly formatted in Markdown? - **see [Github Markdown guide](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet)**
- [x] Have you used the correct folder and file structure? - **see [Contribution Guidelines](https://github.com/section-io/engineering-education/blob/master/CONTRIBUTING.md)**
- [x] Is your article over 750 words? - **Tool**: [Wordcounter.net](https://wordcounter.net)
- [x] Have you used our preferred heading structure? - **[H3 (###) and up](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet#headers)**
- [x] Does your article provide enough value and detail about your topic? - **Articles should be clear, accurate, and fully explained.**
- [x] Can your article be understood by beginners? - **Assume the audience is smart but has no prior exposure to the common terminology in your article.**
- [x] Have you included a hero image that is 600x400 pixels and have the copyright to use it? - **Tools:** [Pixlr Image Editor](https://pixlr.com/e) for resizing and [Unsplash](https://unsplash.com) for Creative Commons images
- [x] In your PR - add a comment that states **["This fixes #(enter your Idea Content Form #)"](https://youtu.be/TKJ4RdhyB5Y?t=278)** to link and close your Idea Content (issue) when the PR is merged.
      

#### Grammar Checks
- [x] Have you spellchecked and grammar checked your article? - **Tool:** [Grammarly](https://grammarly.com)
- [x] Have you checked your article for readability? - **Tool:** [Hemmingway](http://www.hemingwayapp.com)
- [ ] Have you added sources for quotes and images that aren't yours?

#### Technical Checks
- [x] Are your code snippets properly formatted for syntax highlighting - **see [Syntax guide](https://gohugo.io/content-management/syntax-highlighting)**

### Contribution Guidelines
For first-time contributors and for more details, **see [Contributing Guidelines](https://github.com/section-io/engineering-education/blob/master/CONTRIBUTING.md)**

this fixes #452

### CODE REVIEW

**Comment by hectorkambow** [comment]
@ninjaginja  
👋  Good afternoon Molly - wanted to ask if you could give this Kotlin Collections article a tech review whenever you have a moment 🚀 
Thank you

**Comment by ninjaginja** [comment]
@LinusMuema Great writeup! I see that you included a repl.it link to the full code, but additionally, the article should include code fences with relevant methods that you're discussing as you introduce them. Can you please add those as well?

**Comment by LinusMuema** [comment]
By code fences, do you mean mentioning the specific methods or what do you mean....

**Comment by ninjaginja** [comment]
I mean actual code snippets in the markdown. For example:

```kotlin
fun main(args: Array<String>) {
      val arr = listOf("pizza", "burgers", "tea", "coffee", "croissant", "bread", "tea", "burgers")
    
    // Call the functions below and pass **arr** as an argument
    arrays(arr)
}
```

**Comment by LinusMuema** [comment]
Oh...okay.
Lemme do that

**Comment by LinusMuema** [comment]
Hi @ninjaginja 
I have added the code snippets

**Comment by ninjaginja** [comment]
Thanks @LinusMuema !

**Pull request merged**
