### PR TITLE
Converting a Static Site to a Dynamic NodeJS Web App Part 1

### PR DESCRIPTION
**Pull request by louisefindlay23**
Added my second article for consideration. It’s an introduction to NodeJS and NPM and how to get a basic Express server running to serve static web files. Aimed at front-end developers (who can already create basic websites using HTML, CSS and JS.)

Would be part of a series about how front-end developers can get started with back-end development. Dovetails nicely with my first article Getting to Grips with Databases - Part 1.

Title is a work in progress. Alternatives could be, From Front-End to Full-Stack: Part 1 - Creating Your First Server, From Static Site to Dynamic Web App: Part 1 - Adding a Server or From Static Site to Dynamic Web App: Part 1 - Creating Your First Server or for something simpler, How to Create Your First Web Server because it links to a series at the end of the article.

Thinking of retaining the From Front-End to Full-Stack title however for a long-form article encompassing both Getting to Grips with Databases and Static to Dynamic Website series.

### CODE REVIEW

**Comment by louisefindlay23** [comment]
Can you also update my bio, please?

Louise Findlay is a front-end web developer and 3rd year Software Development student at Robert Gordon University. She's designed and developed over 20 static websites, WordPress websites and mobile web apps. You can view her portfolio: [louisefindlay.com](https://louisefindlay.com) or connect with her on Twitter [@louisefindlay23](https://twitter.com/louisefindlay23).

**Comment by hectorkambow** [comment]
Good afternoon @louisefindlay23 
Thank you for your work on this article. Wanted to share some of our technical review committee suggestions for you before we push this to production:

"We wanted to ask if you could include part 2 (pending) in this post? We prefer to have complete articles when it comes to tutorials on how to build something. It would be frustrating for somebody to get to the end of this article without having gotten to the EJS portion that is talked about in the intro. Moving forward tutorials should be complete the objectives in their entirety."
🚀

**Comment by louisefindlay23** [comment]
Hi @hectorkambow. Thanks for the feedback. I've added the second part of this article (most of it) but it's getting pretty long over 1200 words. In your email, it mentions article length should be 500-750 words. 

I still need to add a bit about passing server-side variables to the front-end and briefly mention APIs. Though that would probably cross-over into a seperate article about easy API usage and I'd go into more depth about APIs and EJS templating there.

**Comment by louisefindlay23** [comment]
Finished the last section of the article. Made some notes/suggested changes in bold/strikethrough.

**Comment by louisefindlay23** [comment]
Updated to the new guidelines in #106.

**Pull request closed without merging**
