### PR TITLE
Is Object-Oriented Overrated?

### LINKED ISSUE #1152: Is Object-Oriented Overrated?
### Brief Summary: 
Most professional programming languages are object-oriented, including Java and the C languages. However, their key features (such as encapsulation and inheritance) have come under attack many times in recent memory. Object-oriented detractors claim these features are overcomplicated, and make code writing and maintenance more difficult. We will explore these arguments, and their counters, to better understand the cases where object-oriented programming is more or less useful.

### Key Takeaways: 
What are the 3-5 most important things the reader should understand or be able to do after reading this article?
- Recognize the unique features of the object-oriented paradigm.
- Understand arguments that these features are counterproductive for professional programming tasks.
- Understand the counterarguments to the above.

### References: 
- https://medium.com/better-programming/object-oriented-programming-the-trillion-dollar-disaster-92a4b666c7c7
- https://thenewstack.io/why-are-so-many-developers-hating-on-object-oriented-programming/
- https://stackoverflow.blog/2020/09/02/if-everyone-hates-it-why-is-oop-still-so-widely-spread/
- https://www.youtube.com/watch?v=QM1iUe6IofM

### PR DESCRIPTION
**Pull request by nicholaskross**
#### Preliminary Checks - Formatting and Structure 
- [x] Does your article follow any of the suggested structure formats? - **see [example formats](https://github.com/section-io/engineering-education/blob/master/CONTRIBUTING.md#example-format-structure)**
- [x] Is your article properly formatted in Markdown? - **see [Github Markdown guide](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet)**
- [x] Have you used the correct folder and file structure? - **see [Contribution Guidelines](https://github.com/section-io/engineering-education/blob/master/CONTRIBUTING.md)**
- [x] Is your article over 750 words? - **Tool**: [Wordcounter.net](https://wordcounter.net)
- [x] Have you used our preferred heading structure? - **[H3 (###) and up](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet#headers)**
- [x] Does your article provide enough value and detail about your topic? - **Articles should be clear, accurate, and fully explained.**
- [x] Can your article be understood by beginners? - **Assume the audience is smart but has no prior exposure to the common terminology in your article.**
- [x] Have you included a hero image that is 600x400 pixels and have the copyright to use it? - **Tools:** [Pixlr Image Editor](https://pixlr.com/e) for resizing and [Unsplash](https://unsplash.com) for Creative Commons images
- [x] In your PR - add a comment that states **["This fixes #(enter your Idea Content Form #)"](https://youtu.be/TKJ4RdhyB5Y?t=278)** to link and close your Idea Content (issue) when the PR is merged.

**NOTE: (1st time contributors - submit ONLY one article to get familiar with the process and style-once published, you can then submit any number of articles.)**
      
#### Grammar Checks
- [x] Have you spellchecked and grammar checked your article? - **Tools:** [Write&Improve](https://writeandimprove.com/?lang=en-GB) - [ProWritingAid](https://prowritingaid.com/) -  [Grammarly](https://grammarly.com) 
- [x] Have you checked your article for readability? - **Tool:** [Hemmingway](http://www.hemingwayapp.com)
- [x] Have you added sources for quotes and images that aren't yours?

#### Technical Checks
- [x] Are your code snippets properly formatted for syntax highlighting - **see [Syntax guide](https://gohugo.io/content-management/syntax-highlighting)**

### Contribution Guidelines
For first-time contributors and for more details, **see [Contributing Guidelines](https://github.com/section-io/engineering-education/blob/master/CONTRIBUTING.md)**

Article examining the arguments against and in favor of OOP.

This fixes #1152.

### CODE REVIEW

**Comment by lalith1403** [comment]
@nicholaskross this PR includes files the to the previous article on optimization. Can you delete those files and let us know?

**Comment by nicholaskross** [comment]
@lalith1403 How do I delete the files from just this branch?

**Comment by lalith1403** [comment]
Are you using vscode as your editor? 

Use this as a [resource](https://stackoverflow.com/questions/38743912/remove-a-file-from-a-git-pull-request).

Text me on slack if you need further help, it would be easier to communicate.

**Review by lalith1403 — APPROVED** [review]
You present an interesting take on the pros and cons of object-oriented programming. I learned a lot from it—a well-written article. Congratulations on your first article.

**Comment by hectorkambow** [comment]
image

@nicholaskross  

👋  Was just getting ready to publish your other article but I'm noticing there is a merge conflict - my guess it was the deleted old index files. 

Every article should be its own separate branch on your text editor - create new branch put theses files into that branch - with that branch create a new PR. You can then close this PR and re-submit a Fresh new PR. 

You can leave out your author page -since it was already submitted in your 1st article - that is only needed once unless changing it.

**Comment by nicholaskross** [comment]
@hectorkambow Okay! So I should:
- Update the `oo-overrated` branch with my `constraint-satisfaction` stuff from `master`.
- Commit that change so it shows up in this PR (and removes the merge conflict).
Sound okay?

**Comment by hectorkambow** [comment]
> @hectorkambow Okay! So I should:
> 
> * Update the `oo-overrated` branch with my `constraint-satisfaction` stuff from `master`.
> * Commit that change so it shows up in this PR (and removes the merge conflict).
>   Sound okay?

I believe that is it. 🤔  
You want to update your repo (not the branch) then create a new branch off the updated repo - in that new branch you will only place the object oriented article files. 

I believe you should be able to delete the constraint branch all together. 

The new branch with just the object oriented files will then be in the new pull request. 

I hope that helps. 


Ultimatlely it is as if you are submitting a new article all together. just with the files from this PR. (object oriented files)

**Comment by nicholaskross** [comment]
Alright, I created a new branch and PR, and updated my repo! New PR [here](https://github.com/section-io/engineering-education/pull/1495).

**Pull request closed without merging**
