### PR TITLE
Advantages and Disadvantages of VMs vs. Containers: Part 1

### PR DESCRIPTION
**Pull request by Jscottoz**
Here is my first article, I believe that I didn't create the link correctly on the word "study" so I just provided the URL that the word should be linked to. I plan on writing a part 2 that outlines the disadvantages of VMs vs. Containers.

### CODE REVIEW

**Comment by ninjaginja** [comment]
@Jscottoz Thanks for sending this over! In this case, I think it would be better to consolidate the advantages and disadvantages within the same piece. Feel free to add the disadvantages to this article when ready.

**Comment by Jscottoz** [comment]
Wouldn’t it be a little longer than 750 words?

**Comment by ninjaginja** [comment]
Yes, that's likely, but we always err on the side of substance and value for the audience, rather than length ;)

**Comment by Jscottoz** [comment]
Sounds good, I will add that and send it over.

**Comment by ninjaginja** [comment]
Awesome! Look forward to reviewing it :)

**Comment by Jscottoz** [comment]
Just updated the file. :)

**Comment by Jscottoz** [comment]
This last commit I made the title of the article is "Containers vs. VMs: Advantages and Disadvantages", just omit the "part 1"

**Comment by hectorkambow** [comment]
Migrated to [this PR](https://github.com/section-io/engineering-education/pull/91/files)

**Pull request closed without merging**
