### PR TITLE
Create What-are-VPNs.md

### PR DESCRIPTION
**Pull request by michaelzanoff**
What are VPNs and Why should you use one?
By : Michael Zanoff

### CODE REVIEW

**Comment by ninjaginja** [comment]
@michaelzanoff can you please send a short author bio and headshot to accompany the article?

**Comment by michaelzanoff** [comment]
Michael Zanoff is a freshman at Colorado School of Mines. His passion for the design process and robotics has led him to pursue a degree in Mechanical Engineering. He enjoys keeping up with new technology and learning about the world around him.

IMG_3888

**Comment by michaelzanoff** [comment]
Let me know if I need to add any more information!

Thanks!

**Comment by ninjaginja** [comment]
Great! Thanks @michaelzanoff ! Just pushed to production :)

**Comment by michaelzanoff** [comment]
Thank you!

**Pull request closed without merging**
