### PR TITLE
First Post!!, introduction to Recurrent Neural Networks

### PR DESCRIPTION
**Pull request by rohanreddych**
Hey guys, this is my first post to section.io please let me know if this post meets the community guidelines and standards, and I wanted to write another post as this might become too large. I used latex let me know if anything does not render I used stackedit.io and it worked fine.

### CODE REVIEW

**Comment by rohanreddych** [comment]
About the author

>Rohan Reddy is an undergraduate student at the University of Hyderabad pursuing a degree in Computer Science. Rohan is particularly interested in machine learning and web development.

**Comment by ninjaginja** [comment]
Thanks @rohanreddych. We've got this article in our technical review queue. I'll let you know if anything needs further attention :)

**Comment by hectorkambow** [comment]
Good afternoon @rohanreddych :
Thank you for your work on this article. 
I wanted to share our technical review committee suggestions/edits for you before we push this to production:

"We think it needs a full re-think by the author....we doubt the content is accessible to anyone that does not already know RNNs

We suggest either 1) figure out how to explain RNNs insightfully and less technically to increase accessibilty or 2) Allow the other blogs to explain how RNNs work and use this article to explain, clearly, insightfully, and with some specific details, the application of RNNs. Use some/all of scenarios presented here (lines 90+) but expand on them."

**Comment by rohanreddych** [comment]
@hectorkambow  should i also rewrite   the second part of this. https://github.com/section-io/engineering-education/pull/67

**Comment by hectorkambow** [comment]
> @hectorkambow should i also rewrite the second part of this. #67

@rohanreddych - it might make sense to revisit it as well - if it was building off your 1st RNN article and had a similar approach - (since our team hasn't had a chance to review the second part yet) - but it might be good to apply some of the same added insight and substance to both. 

It would be good to explain any new terminology when introduced. Assume the reader is smart but has no prior exposure to the common terminology.

**Pull request closed without merging**
