### PR TITLE
Software Testing Part 2 - Introduction to Test-Driven Development

### PR DESCRIPTION
**Pull request by Quadrisheriff**
#### Preliminary Checks - Formatting and Structure 
- [x] Does your article follow any of the suggested structure formats? - **see [example formats](https://github.com/section-io/engineering-education/blob/master/CONTRIBUTING.md#example-format-structure)**
- [x] Is your article properly formatted in Markdown? - **see [Github Markdown guide](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet)**
- [x] Have you used the correct folder and file structure? - **see [Contribution Guidelines](https://github.com/section-io/engineering-education/blob/master/CONTRIBUTING.md)**
- [x] Is your article over 750 words? - **Tool**: [Wordcounter.net](https://wordcounter.net)
- [x] Have you used our preferred heading structure? - **[H3 (###) and up](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet#headers)**
- [x] Does your article provide enough value and detail about your topic? - **Articles should be clear, accurate, and fully explained.**
- [x] Can your article be understood by beginners? - **Assume the audience is smart but has no prior exposure to the common terminology in your article.**
- [x] Have you included a hero image that is 600x400 pixels and have the copyright to use it? - **Tools:** [Pixlr Image Editor](https://pixlr.com/e) for resizing and [Unsplash](https://unsplash.com) for Creative Commons images
- [x] In your PR - add a comment that states **["This fixes #(enter your Idea Content Form #)"](https://youtu.be/TKJ4RdhyB5Y?t=278)** to link and close your Idea Content (issue) when the PR is merged.

**NOTE: (1st time contributors - submit ONLY one article to get familiar with the process and style-once published, you can then submit any number of articles.)**
      
#### Grammar Checks
- [x] Have you spellchecked and grammar checked your article? - **Tools:** [Write&Improve](https://writeandimprove.com/?lang=en-GB) - [ProWritingAid](https://prowritingaid.com/) -  [Grammarly](https://grammarly.com) 
- [x] Have you checked your article for readability? - **Tool:** [Hemmingway](http://www.hemingwayapp.com)
- [x] Have you added sources for quotes and images that aren't yours?

#### Technical Checks
- [x] Are your code snippets properly formatted for syntax highlighting - **see [Syntax guide](https://gohugo.io/content-management/syntax-highlighting)**

### Contribution Guidelines
For first-time contributors and for more details, **see [Contributing Guidelines](https://github.com/section-io/engineering-education/blob/master/CONTRIBUTING.md)**

### CODE REVIEW

**Comment by Quadrisheriff** [comment]
This fixes #719

**Comment by hectorkambow** [comment]
[Software Testing Part 2 - Introduction to Test-Driven Development #785.pdf](https://github.com/section-io/engineering-education/files/5625405/Software.Testing.Part.2.-.Introduction.to.Test-Driven.Development.785.pdf)
@Quadrisheriff  
👋  
Thank you for submitting your Software testing article - upon passing it through our 3rd party plagiarism checker it raised a couple red flags. (see attachement) 

Some were code related - but we should always be using new, fresh, and unique content and code for our tutorials or examples. 

👍

**Comment by Quadrisheriff** [comment]
Thanks Hector, I have gone through the attachment. The code samples that were flagged are outputs from the testing framework that I used(pytest). Those are not original code samples, they just tell me if my tests are failing or passing and I think the outputs will be the same for everybody everywhere.

**Review by adrianmurage — APPROVED** [review]
@Quadrisheriff 
Great article, however, there were several small errors that would be corrected if you use the reader first approach I highlighted in the review of part one of this series.
Such little things show neglect and lack of polishing of your articles on your end and in the future, it will be penalized.

Make a point of going through the commits I made

**Comment by adrianmurage** [comment]
@hectorkambow 
This article is ready for final review

**Pull request merged**
