### PR TITLE
Projection in MongoDB

### PR DESCRIPTION
**Pull request by HARITJOSHI1**
Created a folder in the article folder named projection-in-mongodb in which 2 files are there, one is the index.md file which is the main article and the other one is the hero image.
This is my first time posting an article for the section so in the author's folder I have created a folder named harit-joshi in which 2 files are there, one is index.md which gives my info and the other one is an avatar.jpeg file which is my photograph.

My article is on the topic "Projection in MongoDB " which gives full information about what is projection and how it works with different examples and also its application.

### CODE REVIEW

**Comment by HARITJOSHI1** [comment]
### Article Checklist
#### Preliminary Checks - Formatting and Structure 
- [x]  Does your article follow any of the suggested structure formats? - **see [example formats](https://github.com/section-io/engineering-education/blob/master/CONTRIBUTING.md#example-format-structure)**

- [x] Is your article properly formatted in Markdown? - **see [Github Markdown guide](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet)**
- [x] Have you used the correct folder and file structure? - **see [Contribution Guidelines](https://github.com/section-io/engineering-education/blob/master/CONTRIBUTING.md)**
- [x] Is your article over 750 words? - **Tool**: [Wordcounter.net](https://wordcounter.net)
- [x] Have you used our preferred heading structure? - **[H3 (###) and up](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet#headers)**
- [x] Does your article provide enough value and detail about your topic? - **Articles should be clear, accurate, and fully explained.**
- [x] Can your article be understood by beginners? - **Assume the audience is smart but has no prior exposure to the common terminology in your article.**
- [x] Have you included a hero image that is 600x400 pixels and have the copyright to use it? - **Tools:** [Pixlr Image Editor](https://pixlr.com/e) for resizing and [Unsplash](https://unsplash.com) for Creative Commons images
- [x] In your PR - add a comment that states **["This fixes #(enter your Idea Content Form #)"](https://youtu.be/TKJ4RdhyB5Y?t=278)** to link and close your Idea Content (issue) when the PR is merged.

**NOTE: (1st time contributors - submit ONLY one article to get familiar with the process and style-once published, you can then submit any number of articles.)**
      
#### Grammar Checks
- [x] Have you spellchecked and grammar checked your article? - **Tools:** [Write&Improve](https://writeandimprove.com/?lang=en-GB) - [ProWritingAid](https://prowritingaid.com/) -  [Grammarly](https://grammarly.com) 
- [x] Have you checked your article for readability? - **Tool:** [Hemmingway](http://www.hemingwayapp.com)
- [x] Have you added sources for quotes and images that aren't yours?

#### Technical Checks
- [x] Are your code snippets properly formatted for syntax highlighting - **see [Syntax guide](https://gohugo.io/content-management/syntax-highlighting)**

### Contribution Guidelines
For first-time contributors and for more details, **see [Contributing Guidelines](https://github.com/section-io/engineering-education/blob/master/CONTRIBUTING.md)**

This fixes #1032

**Comment by HARITJOSHI1** [comment]
@zolomohan what is the progress of my article

**Comment by zolomohan** [comment]
@HARITJOSHI1 Waiting for Plagiarism check from a manager. I'll start with the preliminary revision once it's done.

**Comment by HARITJOSHI1** [comment]
> @HARITJOSHI1 Waiting for Plagiarism check from a manager. I'll start with the preliminary revision once it's done.

OK sir

**Comment by zolomohan** [comment]
You can just call me Mohan 😅

**Comment by HARITJOSHI1** [comment]
> You can just call me Mohan 😅

How much time this check will take?

**Comment by HARITJOSHI1** [comment]
@hectorkambow @zolomohan any updates ?

**Comment by zolomohan** [comment]
I'll let you know once the plagiarism check is done.

**Comment by hectorkambow** [comment]
[Projection in MongoDB #1095.pdf](https://github.com/section-io/engineering-education/files/5779642/Projection.in.MongoDB.1095.pdf)
@HARITJOSHI1  
👋  Good evening 
Upon running your article through our 3rd party plagiarism checker it raised quite a few flags and the % was a bit higher than we typically like to see. 

Please revisit the article and make sure we are creating unique content and added sources where needed. 
The content should still be original 🚀

**Comment by HARITJOSHI1** [comment]
> [Projection in MongoDB #1095.pdf](https://github.com/section-io/engineering-education/files/5779642/Projection.in.MongoDB.1095.pdf)
> @HARITJOSHI1  
> 👋  Good evening 
> Upon running your article through our 3rd party plagiarism checker it raised quite a few flags and the % was a bit higher than we typically like to see. 
> 
> Please revisit the article and make sure we are creating unique content and added sources where needed. 
> The content should still be original 🚀 
> 

Sir can you please review on some points in my article where flags were raised?

**Comment by hectorkambow** [comment]
> > [Projection in MongoDB #1095.pdf](https://github.com/section-io/engineering-education/files/5779642/Projection.in.MongoDB.1095.pdf)
> > @HARITJOSHI1
> > 👋  Good evening
> > Upon running your article through our 3rd party plagiarism checker it raised quite a few flags and the % was a bit higher than we typically like to see.
> > Please revisit the article and make sure we are creating unique content and added sources where needed.
> > The content should still be original 🚀
> 
> Sir can you please review on some points in my article where flags were raised?

Are you able to download the PDF. that has all the point underlined.

**Comment by HARITJOSHI1** [comment]
> > > [Projection in MongoDB #1095.pdf](https://github.com/section-io/engineering-education/files/5779642/Projection.in.MongoDB.1095.pdf)
> > > @HARITJOSHI1
> > > 👋  Good evening
> > > Upon running your article through our 3rd party plagiarism checker it raised quite a few flags and the % was a bit higher than we typically like to see.
> > > Please revisit the article and make sure we are creating unique content and added sources where needed.
> > > The content should still be original 🚀
> > 
> > Sir can you please review on some points in my article where flags were raised?
> 
> Are you able to download the PDF. that has all the point underlined.

No sir

**Comment by zolomohan** [comment]
image

**Pull request closed without merging**
