### PR TITLE
How to use databinding in android using kotlin

### LINKED ISSUE #663: How to use databinding in Android using Kotlin
### Brief Summary: 
Databinding allows developers to bind the UI components or widgets to their data sources. It eliminates a lot of boiler plate code since the widgets are updated automatically in case of any data changes. Therefore, databinding can allow you to create productive applications with less code.

### Key Takeaways: 
- Understand what databinding in android entails
- Know how to implement databinding in an Android project using Kotlin
- Debug errors resulting from databinding

### References: 
https://developer.android.com/topic/libraries/data-binding#:~:text=Data%20Binding%20Library%20Part%20of,that%20calls%20UI%20framework%20methods.

### PR DESCRIPTION
**Pull request by WanjaMIKE**
Fixes #663 

#### Preliminary Checks - Formatting and Structure 
- [x] Does your article follow any of the suggested structure formats? - **see [example formats](https://github.com/section-io/engineering-education/blob/master/CONTRIBUTING.md#example-format-structure)**
- [x] Is your article properly formatted in Markdown? - **see [Github Markdown guide](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet)**
- [x] Have you used the correct folder and file structure? - **see [Contribution Guidelines](https://github.com/section-io/engineering-education/blob/master/CONTRIBUTING.md)**
- [x] Is your article over 750 words? - **Tool**: [Wordcounter.net](https://wordcounter.net)
- [x] Have you used our preferred heading structure? - **[H3 (###) and up](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet#headers)**
- [x] Does your article provide enough value and detail about your topic? - **Articles should be clear, accurate, and fully explained.**
- [x] Can your article be understood by beginners? - **Assume the audience is smart but has no prior exposure to the common terminology in your article.**
- [x] Have you included a hero image that is 600x400 pixels and have the copyright to use it? - **Tools:** [Pixlr Image Editor](https://pixlr.com/e) for resizing and [Unsplash](https://unsplash.com) for Creative Commons images
- [x] In your PR - add a comment that states **["This fixes #(enter your Idea Content Form #)"](https://youtu.be/TKJ4RdhyB5Y?t=278)** to link and close your Idea Content (issue) when the PR is merged.
      

#### Grammar Checks
- [x] Have you spellchecked and grammar checked your article? - **Tools:** [Write&Improve](https://writeandimprove.com/?lang=en-GB) - [ProWritingAid](https://prowritingaid.com/) -  [Grammarly](https://grammarly.com) 
- [x] Have you checked your article for readability? - **Tool:** [Hemmingway](http://www.hemingwayapp.com)
- [x] Have you added sources for quotes and images that aren't yours?

#### Technical Checks
- [x] Are your code snippets properly formatted for syntax highlighting - **see [Syntax guide](https://gohugo.io/content-management/syntax-highlighting)**

### Contribution Guidelines
For first-time contributors and for more details, **see [Contributing Guidelines](https://github.com/section-io/engineering-education/blob/master/CONTRIBUTING.md)**

### CODE REVIEW

**Comment by hectorkambow** [comment]
👋 Thank you for submitting this PR - we will review it ASAP - all PRs go into our queue will be looked over before being approved to be published.

**Comment by hectorkambow** [comment]
Just an FYI - moving forward - lets please only create a PR once the .md file is fully ready to be reviewed - any changes can be made on your personal forked repo.

**Comment by WanjaMIKE** [comment]
Noted

**Review by kayere — CHANGES_REQUESTED** [review]
Great topic @WanjaMIKE. However, I feel that you have gone out of scope. You have talked more about Mvvm architecture components. I have seen you explaining the functions of the ViewModel and ViewModel Factory, which is not really necessary in this article. You forgot the main topic of the article. You have covered less about data binding. 
Please revise the article and make sure to give more relevant details on the main subject. Omit details that are not necessary.
Another thing, avoid including the package name and imports in your code snippets. They are not really necessary.

**Comment by WanjaMIKE** [comment]
Hello, I have made the changes.
Please note that databinding requires mvvm. A viewmodel needs to be binded to the layout so as data can be accessed directly. EditTexts have been binded to specific variables in the viewmodel. Similarly, functions in the viewmodel have been binded to the layout. This is why some explanation about the viewmodel was needed. Sub section 5 goes into the layout and provides the databinding steps now.

**Review by kayere — APPROVED** [review]
Hello @WanjaMIKE, I understand that you need the Viewmodel in the application. I only implied that you do not need to explain its function in the application since you already did that in your previous article. Otherwise, the changes you made were sufficient. Great work.

**Comment by WanjaMIKE** [comment]
@kayere Noted. Thanks

**Comment by hectorkambow** [comment]
plagiarism check done

**Pull request merged**
