### PR TITLE
Google Search Console: An Introduction

### PR DESCRIPTION
**Pull request by louisefindlay23**
The article is a introduction to Google Search Console. 

It instructs how to add a site (property), verify it, submit a sitemap (will link to in-review Sitemap article) and find and fix crawler errors. 

Also, briefly mentions how to use it to increase SEO and how to redirect properly through the Change of Address tool.

### CODE REVIEW

**Comment by louisefindlay23** [comment]
Header image: 
Google Search Console Section Cover

**Comment by louisefindlay23** [comment]
@ninjaginja, the external image linked to a Loom Video when clicked (limitations of Markdown) that showed the process of verifying a domain on Google Search Console. 

Not a vital part of the article though if you prefer it removed.

**Comment by ninjaginja** [comment]
Great article, @louisefindlay23 ! I think it could be even better if you added some supporting screenshots throughout. There are quite a few references to buttons and on-screen instructions, and they're a bit abstract without the visuals. Could you go back through and add corresponding screenshots that document the process, ensuring that all of the image files are added within the article directory and properly referenced in the .md file (i.e. /google-search-console-introduction/image-file-name.jpg)? Thanks!

**Comment by ninjaginja** [comment]
Ah, just saw your comment @louisefindlay23 regarding the loom video. I didn't realize it was a video; it looked like a static image when I clicked through. We prefer to host images on-domain rather than linking out externally.

**Comment by louisefindlay23** [comment]
Thanks @ninjaginja. Added some screenshots of the Search Console and Sitemap Generator.

**Pull request merged**
