### PR TITLE
React Native Razorpay Integration

### PR DESCRIPTION
**Pull request by zolomohan**
#### Preliminary Checks - Formatting and Structure 
- [x] Does your article follow any of the suggested structure formats? - **see [example formats](https://github.com/section-io/engineering-education/blob/master/CONTRIBUTING.md#example-format-structure)**
- [x] Is your article properly formatted in Markdown? - **see [Github Markdown guide](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet)**
- [x] Have you used the correct folder and file structure? - **see [Contribution Guidelines](https://github.com/section-io/engineering-education/blob/master/CONTRIBUTING.md)**
- [x] Is your article over 750 words? - **Tool**: [Wordcounter.net](https://wordcounter.net)
- [x] Have you used our preferred heading structure? - **[H3 (###) and up](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet#headers)**
- [x] Does your article provide enough value and detail about your topic? - **Articles should be clear, accurate, and fully explained.**
- [x] Can your article be understood by beginners? - **Assume the audience is smart but has no prior exposure to the common terminology in your article.**
- [x] Have you included a hero image that is 600x400 pixels and have the copyright to use it? - **Tools:** [Pixlr Image Editor](https://pixlr.com/e) for resizing and [Unsplash](https://unsplash.com) for Creative Commons images
- [x] In your PR - add a comment that states **["This fixes #(enter your Idea Content Form #)"](https://youtu.be/TKJ4RdhyB5Y?t=278)** to link and close your Idea Content (issue) when the PR is merged.

**NOTE: (1st time contributors - submit ONLY one article to get familiar with the process and style-once published, you can then submit any number of articles.)**
      
#### Grammar Checks
- [x] Have you spellchecked and grammar checked your article? - **Tools:** [Write&Improve](https://writeandimprove.com/?lang=en-GB) - [ProWritingAid](https://prowritingaid.com/) -  [Grammarly](https://grammarly.com) 
- [x] Have you checked your article for readability? - **Tool:** [Hemmingway](http://www.hemingwayapp.com)
- [x] Have you added sources for quotes and images that aren't yours?

#### Technical Checks
- [x] Are your code snippets properly formatted for syntax highlighting - **see [Syntax guide](https://gohugo.io/content-management/syntax-highlighting)**

### Contribution Guidelines
For first-time contributors and for more details, **see [Contributing Guidelines](https://github.com/section-io/engineering-education/blob/master/CONTRIBUTING.md)**

### CODE REVIEW

**Comment by zolomohan** [comment]
This fixes #743

**Comment by hectorkambow** [comment]
👋 Thank you for submitting this PR - we will review it ASAP - all PRs go into our queue will be looked over before being approved to be published.

**Review by WanjaMIKE — APPROVED** [review]
Nice article. Easy to follow. Provided code snippets work as expected. Only a few errors such as image links which were corrected. Keep up. Thanks

**Comment by zolomohan** [comment]
@WanjaMIKE Thank you for taking the time to review my article.

**Comment by hectorkambow** [comment]
@zolomohan  
👀  

I think there are two image that are in the PR but not in the article. 

One I believe is the 'payment_flow.png' 

I can not figure out the 2nd missing image. 

🤔

**Comment by zolomohan** [comment]
@hectorkambow 

Only the `payment_flow.png` was not included in the article. I meant to delete it but it somehow slipped past me. Sorry.
There's no second missed image. I think you may have counted `hero.jpg`.

**Comment by zolomohan** [comment]
@hectorkambow

Only the `payment_flow.png` was not included in the article. I meant to delete it but it somehow slipped past me. Sorry for the trouble.
There's no second image. I think you may have counted hero.jpg.

**Comment by zolomohan** [comment]
Also @hectorkambow. At some places, I noticed that you replaced Modal with Model. It's actually [Modal](https://en.wikipedia.org/wiki/Modal_window). I reverted them back.

**Pull request merged**
