### PR TITLE
Introduction to Robotic Process Automation

### PR DESCRIPTION
**Pull request by JudyNduati**
I have added an index.md file and header image hero.jpg
Article Description
This article describes RPA. It explains how it differs from traditional automation in terms of features and functionality. It also explains the importance of RPA and why we should consider it for enterprises. The main take away from the article is how RPA differs from automation and how it makes business processes easier and cheaper.

### CODE REVIEW

**Comment by hectorkambow** [comment]
Plagiarism check is done

**Comment by hectorkambow** [comment]
Good afternoon Gary - happy Monday - hope you had a good weekend. 
Wanted to ask if you could give this "Introduction to Robotic Process Automation" a tech review when you have a moment 🚀 
Thank you

**Review by gwritz — APPROVED** [review]

**Comment by hectorkambow** [comment]
@JudyNduati 👋  Good morning/afternoon - I was just going over your article again - very informative and helpful article - but I think it would add some value if it had a nice conclusion to wrap up your thoughts - perhaps going into what you believe RPA can be like in the future - where the tech will go - or what you see as barriers - anything to finalize your thoughts about the topic and article. 
🚀

**Comment by JudyNduati** [comment]
@gwritz I have added the conclusion

**Pull request merged**
