### PR TITLE
Introduction to Digital Twin Technology

### LINKED ISSUE #694: Introduction to Digital Twin Technology
### Brief Summary: 
Digital twin technology is a concept that integrates software analytics, artificial intelligence and special network graphs to create digital simulation models that replicate physical assets (physical twin). It performs important functions such as optimization of operations in manufacturing processes and driving business value. This article gives readers meaningful information regarding this new technology. 

### Key Takeaways: 
1. What is a Digital Twin?
2. Why is Digital Twin Technology Important?
3. Characteristics of Digital Twin Technology
4. How Digital Twin Technology Works
5. Applications of Digital Twin Technology
6. The Future of Digital Twin Technology

### References: 
file:///C:/Users/ADMIN/AppData/Local/Temp/an-introduction-to-digital-twin-development.pdf

### PR DESCRIPTION
**Pull request by mbaabuones**
#### Preliminary Checks - Formatting and Structure 
- [x] Does your article follow any of the suggested structure formats? - **see [example formats](https://github.com/section-io/engineering-education/blob/master/CONTRIBUTING.md#example-format-structure)**
- [x] Is your article properly formatted in Markdown? - **see [Github Markdown guide](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet)**
- [x] Have you used the correct folder and file structure? - **see [Contribution Guidelines](https://github.com/section-io/engineering-education/blob/master/CONTRIBUTING.md)**
- [x] Is your article over 750 words? - **Tool**: [Wordcounter.net](https://wordcounter.net)
- [x] Have you used our preferred heading structure? - **[H3 (###) and up](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet#headers)**
- [x] Does your article provide enough value and detail about your topic? - **Articles should be clear, accurate, and fully explained.**
- [x] Can your article be understood by beginners? - **Assume the audience is smart but has no prior exposure to the common terminology in your article.**
- [x] Have you included a hero image that is 600x400 pixels and have the copyright to use it? - **Tools:** [Pixlr Image Editor](https://pixlr.com/e) for resizing and [Unsplash](https://unsplash.com) for Creative Commons images
- [x] In your PR - add a comment that states **["This fixes #(enter your Idea Content Form #)"](https://youtu.be/TKJ4RdhyB5Y?t=278)** to link and close your Idea Content (issue) when the PR is merged.

**NOTE: (1st time contributors - submit ONLY one article to get familiar with the process and style-once published, you can then submit any number of articles.)**
      
#### Grammar Checks
- [x] Have you spellchecked and grammar checked your article? - **Tools:** [Write&Improve](https://writeandimprove.com/?lang=en-GB) - [ProWritingAid](https://prowritingaid.com/) -  [Grammarly](https://grammarly.com) 
- [x] Have you checked your article for readability? - **Tool:** [Hemmingway](http://www.hemingwayapp.com)
- [x] Have you added sources for quotes and images that aren't yours?

#### Technical Checks
- [ ] Are your code snippets properly formatted for syntax highlighting - **see [Syntax guide](https://gohugo.io/content-management/syntax-highlighting)**

### Contribution Guidelines
For first-time contributors and for more details, **see [Contributing Guidelines](https://github.com/section-io/engineering-education/blob/master/CONTRIBUTING.md)**

This fixes #694 . This PR has been created because the initial PR has a merge conflict.

### CODE REVIEW

**Review by lalith1403 — APPROVED** [review]

**Comment by hectorkambow** [comment]
👋  
Good evening @mbaabuones - I was giving your article a final review but found many paragraphs could be phrased different as they were a bit difficult to get through. 

Please see the paragraph I changed (to make sure I didn't change the meaning completely) to get an idea of how to restructure the rest of the article. 

We want to avoid using a passive voice in our writing. 

Hope the paragraph I changed helps structure the rest.

**Comment by mbaabuones** [comment]
> 
> 
> 👋
> Good evening @mbaabuones - I was giving your article a final review but found we could phrase many paragraphs different as they were a bit difficult to get through.
> 
> Please see the paragraph I changed (to make sure I didn't change the meaning completely) to get an idea of how to restructure the rest of the article.
> 
> We want to avoid using a passive voice in our writing.
> 
> Hope the paragraph I changed helps structure the rest.

@hectorkambow I accept the changes that you have made. These changes have improved the quality of the article. I appreciate it. I have noticed a slight error in the second sentence of the section 'connectivity'. I have deleted the word 'and'. Please check if this is the right action.

**Comment by lalith1403** [comment]
@mbaabuones I think Hector had asked you to convert all passive sentences into active verbs! I hope you have done that! I only see a minor change in the previous commit. Just checking if all necessary changes have been pushed!

**Comment by mbaabuones** [comment]
> 
> 
> @mbaabuones I think Hector had asked you to convert all passive sentences into active verbs! I hope you have done that! I only see a minor change in the previous commit. Just checking if all necessary changes have been pushed!

@lalith1403 . I think there was a misunderstanding from my end. I apologize for that. I was about to make changes in the other parts of the article, but i realized that @hectorkambow had added some commits (before my minor change). I thought these were the changes he needed. Nevertheless, i have made some other minor changes to ensure passive voice is minimized.

**Pull request merged**
