### PR TITLE
Node mailer

### PR DESCRIPTION
**Pull request by LinusMuema**
This is an article that shows how to send emails using the nodemailer package in a NodeJs server.
The files added are:
`hero.jpg` - source : [Pexels](https://pexels.com)

### CODE REVIEW

**Comment by hectorkambow** [comment]
@LinusMuema - just finishing up a preliminary review on your Node Mailer article - think it looks great to far. 
Wanted to ask if you could include a sum up or conclusion might add value to help wrap the article up.

After that the article will be ready for a tech review before publishing 🚀 

Great work

**Comment by LinusMuema** [comment]
Okay @hectorkambow Let me get to it

**Comment by hectorkambow** [comment]
Hi @AskAlice  👋  - wanted to ask if you could give this Node Mailer a tech review before publishing 🚀 
Thank you 
Also is it Nodemailer or Node Mailer?? 🤔 Or Node.js Mailer?

**Comment by LinusMuema** [comment]
@AskAlice that was exactly my main aim. Education, I did not want to use other services like `Sendgrid` or 	`Mailgun` due to competition and some really pricy plans they have. 😊

**Pull request merged**
