### PR TITLE
Dry manifesto

### PR DESCRIPTION
**Pull request by botahamec**
Title: "A Something Sort-Of Like a DRY-ism-ist Manifesto"
Description: DRY is a very important part of software engineering. Sometimes it seems like you must repeat code even when you don't have to. This tutorial will show you how, using functions, generics, and inheritance.

### CODE REVIEW

**Comment by hectorkambow** [comment]
Good afternoon @manibatra 👋  
Wanted to ask if you could give this DRY article a tech review when you get a chance - before we publish 🚀 
Thank you

**Comment by hectorkambow** [comment]
@ninjaginja  👋  Good morning Molly - wanted to ask if you could give this DRY manifesto article a tech review when you get a moment - wanted to re-assign - since I saw Mani was AFK this week. 
🚀 
Thank you

**Comment by ninjaginja** [comment]
@botahamec The intro to this article is a bit confusing, and seems to be too much of a knock-off from the source that you reference. Plus, the insertion of the DRY Manifesto heading with the Slate Star Codex article link is another very confusing element, as it doesn't relate back to the story that you're introducing in the first paragraph; and you don't actually introduce the concept of DRY manifesto until half-way through the article. I'd suggest revisiting the intro to more clearly introduce the substance that is covered in the second half of the article.

**Comment by botahamec** [comment]
@ninjaginja I think the SSC issue was that it wasn't clear that I was talking about the title, rather than the story. I think that's fixed now.

As for the story, I've added a sentence to the first paragraph to make it more clear how it's related to DRY

**Pull request merged**
